### ISSUE TITLE
JDBI 3 - Handle.close() throws error when connections with autoCommit as false are used 

### ISSUE THREAD

**Issue by vksiva** [jdbi/jdbi#1000]
Raising an issue after a discussion in the forum - https://groups.google.com/d/topic/jdbi/1vTR2Zmt1ZM/discussion
```
Handle handle = jdbi.open();
handle.getConnection().setAutoCommit(false);
handle.begin();
List<String> names = handle.createQuery("select NAME from profile limit 1")
        .mapTo(String.class)
        .list();
handle.commit();
handle.close();
```
The above code throws an error -

```
org.jdbi.v3.core.transaction.TransactionException: Improper transaction handling detected: A Handle with an open transaction was closed. Transactions must be explicitly committed or rolled back before closing the Handle. Jdbi has rolled back this transaction automatically.
```

Please suggest a way of working with connections that have autoCommit as false.

**Comment by qualidafial** [comment]
Unless you're using `CMTTransactionHandler`, `Handle.begin()` is already setting autocommit to false. Any reason you're calling this manually?

**Comment by qualidafial** [comment]
That said, I think I've seen enough error reports about this check that we should provide a config option to disable it.

**Comment by qualidafial** [comment]
Opened PR #1001

**Comment by vksiva** [comment]
(Handle.begin()) Just a superstitious belief hoping that transactions would work ...

**Comment by qualidafial** [comment]
I could see the value in automatically rolling back for some people, but we've also heard from users who prefer to attempt a recovery when a statement fails, rather than automatically rolling back. So adding this behavior as a default is unlikely.

Also please note that the option in #1001 (which is now merged) may be set at the `Jdbi` level (so you only have to set it once) or at the `Handle` level. Whichever works for your use case.

Closing as resolved.
