### ISSUE TITLE
UnableToCreateStatementException: Could not create mapper <(here class name)>

### ISSUE THREAD

**Issue by pitschr** [jdbi/jdbi#1051]
JDBI Version: 3.1.0 (incl. SQL Object)

	org.jdbi.v3.core.statement.UnableToCreateStatementException: Could not create mapper jdbi.issue2.Issue2Test$InnerMyObjectMapper
		at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.rowMapperFor(CustomizingStatementHandler.java:190)
		at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.lambda$configureReturner$0(SqlQueryHandler.java:53)
		at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:157)
		at org.jdbi.v3.sqlobject.statement.internal.SqlQueryHandler.invoke(SqlQueryHandler.java:26)
		at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:162)
		at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:73)
		... lines omitted ...
	Caused by: java.lang.NoSuchMethodException: jdbi.issue2.Issue2Test$InnerMyObjectMapper.<init>()
		at java.lang.Class.getConstructor0(Class.java:3082)
		at java.lang.Class.getConstructor(Class.java:1825)
		at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.rowMapperFor(CustomizingStatementHandler.java:187)
		... 72 more

Not sure if a real issue (more a matter of design) but am reporting so you can decide it by yourself as in 99% cases the mapper should be an own class. It seems it is not possible to use as a mapper which is an inner class.

See attached file how to reproduce (using JUnit 5, H2 database) with minimal code:
[issue2.zip](https://github.com/jdbi/jdbi/files/1847242/issue2.zip)

Workaround is to define a mapper as an own class (e.g. like `ExternalMyObjectMapper` ). Not tested with other mapper types like Column Mapper, Argument, ... . The chance that it will fail as well with those mappers is probably valid.

KR,
Christoph

**Comment by stevenschlansker** [comment]
Hi Christoph, this is a consequence of Java inner classes -- they take a hidden parameter, the instance of the enclosing class, and when we try to construct your mapper we of course do not have any appropriate enclosing instance to use.

The change you highlight, making the class separate, will fix the problem.  Another option is to simply declare the class as `static`, then it becomes a nested class instead of an inner class, and does not require this reference constructor parameter.

Most other Java libraries I'm aware of have similar restrictions (for example Jackson gets this question frequently enough that there's a [blog post on it](http://www.cowtowncoder.com/blog/archives/2010/08/entry_411.html) )

Let us know if it's not clear or if there's misleading documentation on the subject.

**Comment by FredDeschenes** [comment]
Like @stevenschlansker mentioned above, it seems like you can bypass this by making your inner class static **and adding a default public constructor** like this :
```java
...
	public static class InnerMyObjectMapper implements RowMapper<MyObject> {

	        public InnerMyObjectMapper() {
                }

		@Override
		public MyObject map(ResultSet rs, StatementContext ctx) throws SQLException {
                ...
		}
	}
...
```

@stevenschlansker : Just marking the class `static` does not get rid of this, the default constructor has to be added (this might differ depending on your version of Java though, but with 1.8u151 I also have to add the constructor).

This seems to have been caused by a switch from `Class::newInstance()` in [v2](https://github.com/jdbi/jdbi/blob/jdbi2/src/main/java/org/skife/jdbi/v2/sqlobject/ResultReturnThing.java#L38) to `Class::getConstructor()::newInstance()` in [v3](https://github.com/jdbi/jdbi/blob/master/sqlobject/src/main/java/org/jdbi/v3/sqlobject/statement/internal/CustomizingStatementHandler.java#L187).

Changing `CustomizingStatementHandler::rowMapperFor` to use `Class::newInstance()` removes the necessity for having the default constructor.

**Comment by FredDeschenes** [comment]
@stevenschlansker : Yeah nevermind, IntelliJ just wasn't always rebuilding the .class when just adding or removing the `static` keyword so it was giving me incorrect results -_- Adding the constructor triggered the recompile, which of course made it  work but was unnecessary. And yeah there's a bunch of unit tests that wouldn't work if this was broken :P
