### ISSUE TITLE
SqlObject plugin and BindBean: is there a way to specify java.sql.Types for fields/properties?

### ISSUE THREAD

**Issue by igortochansky** [jdbi/jdbi#1096]
For example, 
```java
@lombok.Data
class Address {
    // It is java.sql.Types.VARCHAR
    // JDBI uses VARCHAR by default for strings, so no action is needed
    private final String country;

    // It has to be java.sql.Types.NVARCHAR
    // Is there some way to specify it?
    // It seems that now there is no a good option. There are two workarounds:
    // 1) Create a new class NString and provide an argument factory for it.
    // 2) Use two annotations (see jpa plugin as example: @BindJpa and @Column)
    private final String city;
}

**Comment by igortochansky** [comment]
`@SqlType` will solve the problem but perhaps it would be more general if `@RegisterArgumentFactory`  may be attached to bean properties (and parameters of Dao's method).

**Comment by qualidafial** [comment]
The problem with `@RegisterArgumentFactory` is scope. Once you register an argument factory that works on `String`, it will use that argument for all strings--not just the one you annotated.

I'm not sure that `@SqlType` will do the trick either. You have to call e.g. `setNString()` instead of `setString()` for NVARCHAR types.

I've had a similar issue with `MACADDR` data types in Postgres. Our solution was to introduce a `MacAddress` class and register an argument factory and a column mapper for that type.

I'm trying to imagine how we might use a qualifying annotation system (similar to javax.inject qualifying annotations like `@Named("foo")`, but that would require us to enhance the existing factory APIs to recognize those annotations.

Unfortunately, I think spinning up an `NString` class may be your best option at the moment.

**Comment by igortochansky** [comment]
@qualidafial, in fact I can change DB schema now. So in my current case I will just replace all `varchars` with `nvarchars` in DDL of my tables. Then I will override default argument factory for strings.
However, usually it is not an option and people need to invent something like `NString`, `MacAddress` or pair of custom annotations. In JPA plugin it is  `@BindJpa` and `@Column`.  Actually, i see, that in our projects based on jdbi v2 a similar approach is already used. There are two annotations `@BindSqlType` for bean's properties and `@BindEntity` marked with `org.skife.jdbi.v2.sqlobject.BindingAnnotation`.
It works but it does not look good because you need to write some custom code and also should remember about both annotations:
```java
@lombok.Data
class Entity {
    @BindSqlType(NVARCHAR)
    private String comments;
}

interface Dao {
   // A developer forgot to use own custom annotation to apply @BindSqlType.
   @SqlUpdate("some sql")
   void wrong(@BindBean Entity entity);

   // Here everything is OK
   @SqlUpdate("some sql")
   void ok(@BindEntity Entity entity);
}

**Comment by stnimnul** [comment]
@SqlType(Types.NVARCHAR) is exactly what is needed in this case. Would also be great to bind NULL values with data type from this annotation, instead of Types.NULL.

**Comment by qualidafial** [comment]
I'm pursuing a possible solution that would permit arbitrary qualifying annotations to be used and supported by a new class of argument factory. This is somewhat inspired by the `javax.inject.Qualifier` meta-annotation.

The design so far:

* `QualifiedType` class representing a `java.lang.reflect.Type` with a `Set<Object>` set of qualifiers.
* `QualifiedArgumentFactory` factory interface mirroring `ArgumentFactory`.
* `StatementContext.findArgumentFor(QualifiedType, type, Object value)` method mirrors existing `Type` variant.
* `Argument.findFor(QualifiedType type, Object value)` method mirrors existing `Type` variant.
* `@Qualifier` meta-annotation
* `@NVarchar` proof of concept annotation
* `BuiltInQualifiedArgumentFactory` provides an implementation for `@NVarchar String` arguments.
* Modify named argument finders in core (e.g. `bindBean`, `bindMethods`, `bindFields`) to pay attention to qualifying annotations on the field or method.

Note that I chose to use `Object` instead of `Annotation` as the qualifier type. This is to allow arbitrary qualifiers to be used, and not restrict it to just Java annotations--e.g. Kotlin annotations.

To do:
* Enhance `BindFactory` to honor qualifying annotations.
* Test test test

**Comment by qualidafial** [comment]
Pushed work in progress to branch: https://github.com/jdbi/jdbi/tree/argument-qualifiers

**Comment by igortochansky** [comment]
@qualidafial , sounds like a good design. It will be convenient to add annotations with additional abilities.
For instance, I have a real example when strings are truncated to some length before be written to database.
So people will be able to add something like `@LimitedNVarchar(length = 100)`

**Comment by qualidafial** [comment]
@igortochansky could you build that branch and see if the `@NVarchar` annotation on your Lombok class actually works? I'm going to add tests but if you already have a use case it'd be nice to know if this will actually work.

**Comment by qualidafial** [comment]
Try `@BindFields`

**Comment by igortochansky** [comment]
`@BindFields` does not help because the fields are private in this case.
`type.getFields()` below returns only public fields and it seems to be rather right behavior here.
```java
public class ObjectFieldArguments extends ObjectPropertyNamedArgumentFinder {
    private static final Map<Class<?>, Map<String, Field>> CLASS_FIELDS = ExpiringMap.builder()
        .expiration(10, TimeUnit.MINUTES)
        .expirationPolicy(ExpirationPolicy.ACCESSED)
        .entryLoader((Class<?> type) ->
            Stream.of(type.getFields())
                .collect(toMap(Field::getName, Function.identity())))
        .build();
   // other code...
}

**Comment by qualidafial** [comment]
@igortochansky what database vendor are you using? I'm struggling to find a test case that breaks without the `@NVarchar` qualifier.

**Comment by stnimnul** [comment]
I thought that maybe it is simpler to specify data-type where some value is bounded to - into SQL:
```java
@SqlUpdate ("SELECT * FROM employee e WHERE e.first_name = :firstName#NVARCHAR and e.active = :status#NUMBER")
abstract Employee findEmployee (String firstName, Boolean status) ;
```

This looks more natural for me because Java entity should not always be aware about exact data-type of table column mapped in database. But, SQL should.

**Comment by qualidafial** [comment]
Please take a look at #1160 which is nearing completion.

**Comment by qualidafial** [comment]
NVARCHAR support is merged, and will be included in the 3.6.0 release.

Have you tried the `@Getter(_onMethod=@NVarchar)` approach?

**Comment by TheRealMarnes** [comment]
Closing because the solution is implemented

**Comment by qualidafial** [comment]
@igortochansky The latest version of Lombok added the ability to configure which annotations are copied from fields to getters, setters, and constructor parameters. See our docs at https://github.com/jdbi/jdbi/blob/master/docs/src/adoc/index.adoc#lombok

**Comment by igortochansky** [comment]
@qualidafial, thank you for implementing this feature and sorry for my delayed response.
The documentation looks very good.
