### ISSUE TITLE
Problem using '<' mark in SqlQuery

### ISSUE THREAD

**Issue by changan1995** [jdbi/jdbi#1156]
`    //call insert into oss.
    @SqlUpdate("INSERT INTO temp_expired_log_visit4 SELECT * FROM temp_log_visit WHERE visit_at <= 1500617376201")
    abstract void mvExpired();`
I has a trouble using this Query, it's simply moving from this temp_log_visit to temp_expired_log_visit4;
the condition is visit_at(sometime) < 1500617376201L.

The error log is pretty strange:
`line 1:103: expecting '>', found '<EOF>'`
`  testTruncateExpired(com.borderx.fifthave.db.pg.PgLogVisitDAOTest): org.postgresql.util.PSQLException: ERROR: syntax error at end of input`

I think that somehow the jbi.ondemand() consider < as a start of '<>' rather than less than...

Is there a way to avoid it?

**Comment by TheRealMarnes** [comment]
This is because of the default registered TemplateEngine, which interprets strings like `<foo>` as variables. It glitches like this when you use angle brackets for comparisons. I've had the issue myself...

You can get around this by escaping angle brackets with `\`, IIRC. Or you can set a different TemplateEngine on the context (there are plenty to choose from now), or set it to TemplateEngine.NOP.

**Comment by qualidafial** [comment]
What version are you using? This should be fixed in recent releases.

**Comment by changan1995** [comment]
Oh I just notice I was using jdbi2.
And I kind of find a solution by use > instead of < (lmao)
That works well.

**Comment by changan1995** [comment]
Thank you for your help :)

**Comment by qualidafial** [comment]
Sure thing. My recollection is fuzzy but I believe we addressed this in the v2 branch--you could try version 2.78 and see if that fixes the `<` parsing.

**Comment by qualidafial** [comment]
Closing question as answered. If after upgrading you find that this is still a problem on 2.x, please let us know and we can reopen this issue as a bug.
