### ISSUE TITLE
ArgumentFactory for enums by ordinal

### ISSUE THREAD

**Issue by felipeanchieta** [jdbi/jdbi#1197]
**Scenario**
Currently, during SQL statements building, JDBI translates enums to String using `.name()` method as we can see [here](https://github.com/jdbi/jdbi/blob/v3.3.0/core/src/main/java/org/jdbi/v3/core/argument/BuiltInArgumentFactory.java#L160). That can be replaced by extending `ArgumentFactory` class with a personalized behavior.

**Feature proposal**
In this issue, I suggest this default behavior to be decoupled in such a manner that we will have an `EnumByOrdinalArgumentFactory` (to be written) and an `EnumByNameArgumentFactory` (to be copied), with the latter as the default `ArgumentFactory` for enums, for the matter of compatibility.

By doing so, the developer may easily choose which `ArgumentFactory` he/she will use for mapping a hypothetical enum to their database. JDBI also gains a more decoupled approach.

**Comment by TheRealMarnes** [comment]
This is part of something I've been trying to do for a long time now, namely destructuring the monolithic "BuiltInArgument/Mapper" factories. Just haven't gotten around to a proper implementation yet. My idea was to have it as a configuration option somewhere, e.g. `jdbi.getConfig(Something.class).mapEnumsByName(bool)` instead of bothering the end user with different
