### ISSUE TITLE
less operation sign in SQL throw error

### ISSUE THREAD

**Issue by bathpp** [jdbi/jdbi#1214]
I have a sql file and the query is something like
```
select
    iif( table_id <1000, 0, 1 ) as id,
from TABLE;
```
Calling the query by using dao interface
```
@SqlQuery
@UseClasspathSqlLocator
List<Table> findTables();
```
And it will trigger error
```
org.jdbi.v3.core.statement.UnableToCreateStatementException: Error rendering SQL template: 'select  iif( table_id <1000, 0, 1 ) as id from table; '
```
Adding a back slash ```\<``` will work, but wonder if this could be done in a proper way.

**Comment by TheRealMarnes** [comment]
The default TemplateEngine parses `<foo>` as placeholders. It considers `<` an opening tag and expect the rest of the syntax. Register a different engine for this statement to avoid it (e.g. TemplateEngine.NOP), or as @qualidafial said somewhere if I'm not mistaken, update your jdbi because this is apparently fixed in more recent versions.

**Comment by bathpp** [comment]
Thanks, it get resolved after I update the JDBI version.
