### ISSUE TITLE
JDBI 3.4.0 in maven central

### ISSUE THREAD

**Issue by PascalSchumacher** [jdbi/jdbi#1223]
Just wondering, was 3.4.0 released by mistake?

It is already in maven central: https://search.maven.org/artifact/org.jdbi/jdbi3-core/3.4.0/jar while https://github.com/jdbi/jdbi/blob/master/pom.xml#L26 still contains `3.4.0-SNAPSHOT`.

**Comment by qualidafial** [comment]
@stevenschlansker Did the release commits, tags not get pushed?

**Comment by stevenschlansker** [comment]
@qualidafial @PascalSchumacher I fucked up here, I forgot that the jdbi repository does not automatically `git push` on release (all my other projects do) and the release was done from my work machine.  I'm now no longer employed, so I do not have access to the commits / tags.

`3.4.0` is available, and I could re-create the release, but IMO we should just get 3.4.1 out the door properly soon rather than try to re-construct the past.  I'll spend some time this week doing another pass on the open issues / PRs.

My apologies for bungling this release.
