### ISSUE TITLE
SQL Array with oracle

### ISSUE THREAD

**Issue by fabianedl777** [jdbi/jdbi#1248]
Good afternoon:

Currently I am using JDBI 3.0 and I want to use SQL Array with oracle, I would like to know if there is any implementation to support this.

Thank you very much

**Comment by qualidafial** [comment]
Yes, this isn't very well documented at the moment. What we have right now (http://jdbi.org/#_sql_arrays) is little more than a to-do list for better documentation. I'll try to explain this here and that will hopefully form the basis for better documents on the site.

Jdbi SQL array support requires a little work to set up for each array element type, due to the underlying JDBC APIs we have to work with.

If you look at the [source for PostgresPlugin](https://github.com/jdbi/jdbi/blob/master/postgres/src/main/java/org/jdbi/v3/postgres/PostgresPlugin.java#L55-L64) you'll see an example of what we do in Postgres to support arrays of the types we know are supported in Postgres.

Supporting arrays with Oracle data types will require similar calls, but you'll need to substitute the Oracle DB data type names.

If you would be so kind as to put together a list of Oracle data type names and their corresponding Java types, we would be happy to add an Oracle plugin that registered all those array types.

**Comment by fabianedl777** [comment]
Hi @qualidafial,

I want to use nested table of oracle; Can I record these collections as arrays? or I have to make some additional implementation.

Thank you, for your help.

**Comment by qualidafial** [comment]
I'm not familiar with nested table usage. Can you give an example what it looks like with JDBC?

**Comment by fabianedl777** [comment]
Hi @qualidafial 

For example in oracle i created the nested table using the following script

**CREATE TYPE NUMBER_TABLE AS TABLE OF NUMBER**

After, it excutes the next query using the nested table

**SELECT id, name FROM person WHERE id in (SELECT column_value FROM TABLE(:tableNumber))**

Using oracle jdbc and kotlin, i execute the previous query in the following way.

**val oracleConn = conn.unwrap(OracleConnection::class.java)**
**val desc = ArrayDescriptor("TABLE_NUMBER", oracleConn)**
**val keys: List<Long> = listOf(1L,2L,3L,4L)**
**val array = ARRAY(desc, oracleConn, keys.toLongArray())**
**val sql = "SELECT id, name FROM person WHERE id in (SELECT column_value FROM TABLE(:tableNumber))"**

**var ps: PreparedStatement? = conn.prepareStatement(sql)**
**ps.setArray(1, array)**
**var rs: ResultSet? = ps.executeQuery()**

I have been reviewing the implementation for the oracle array and I see that it is very similar, but I do not know if it is possible to register as it is done in postgresql plugin.

Thank you.

**Comment by qualidafial** [comment]
To support SQL arrays of a particular Java type, you have to tell Jdbi the SQL type name that corresponds to that Java type--this is assuming the Java type is _natively_ supported by the database driver:

```java
jdbi.registerSqlType(long.class, "number")
    .registerSqlType(Long.class, "number");
```

If you want to map a SQL array to some custom type, you have to register a custom SqlArrayType implementation.

**Comment by qualidafial** [comment]
Once you've registered an array type, you can bind any iterable or array of that Java element type, and you can map it into any collection type registered with Jdbi. e.g. if the Guava Jdbi plugin is installed you can map array columns to e.g. `ImmutableSet<YourArrayElementType>`

**Comment by qualidafial** [comment]
Hope this answers your question. Feel free to follow up if you have further questions.
