### ISSUE TITLE
Add convenience method to bind array

### ISSUE THREAD

**Issue by juggernaut** [jdbi/jdbi#1274]
Per @qualidafial 's comment https://github.com/jdbi/jdbi/pull/1264#discussion_r225031970 - it would be nicer to have a `bindArray(column, collection, elementType)` method rather than having to `bindByType`

**Comment by TheRealMarnes** [comment]
Could you specify the types of the variables or use case, please? I'm having a hard time seeing exactly what the issue is...

The code the comment was about is
`bindByType("userIds", Arrays.asList(10, 5, 70), new GenericType<List<Integer>>() {})`
so I'm drawing `String/int, Collection<T>, Class<T>` from your post. But the method of the body would have to just presume the `List` in the `GenericType` then? Can't be right.

If I had to make a guess, I'd actually go for `String/int, Class<T> elementType, T...` as parameters, and make the implementation `Arrays.asList` them, which then of course gives the freedom to presume the `List`. Is that on the right track?

**Comment by qualidafial** [comment]
You don't have to wrap it in list--`SqlArrayFactory` will bind any `Collection` or Java array, provided a `SqlArrayType` is registered for the element type.

I am however intrigued by putting the element type second in the parameter list, so the final parameter can be either a vararg or a collection.

**Comment by stevenschlansker** [comment]
@juggernaut, please check out #1594 which adds these convenience methods!
