### ISSUE TITLE
StringTemplate/JDBI documentation encourages insecure use

### ISSUE THREAD

**Issue by eropple** [jdbi/jdbi#1315]
(edit: this looks like a documentation concern, read further down!)

So I was looking through JDBI for a new project (getting back into using the JVM) a bit and I'm honestly a little befuddled. JDBI seems like a great tool, and oh, cool--StringTemplate's not my favorite way to do a SQL but it's fine. And it reads nicer, with if statements and the like. Let's give that a shot.

My first "uh-oh" happened when PostgreSQL started shouting at me about "keywords" which were strings passed into the template. The SQL isn't...quoted?

I ask myself--self, there's no parameterization at all here, is there? I had best investigate. And sure enough, upon investigation, there isn't. Raw strings passed straight through. Oh no.

--

It's not that this exists, per se. I get the desire for dynamically built SQL and I've done similar with Velocity and with FreeMarker before. But I've done it in severely circumscribed contexts with well-understood and prevalidated data, and in that light my concerns are as follows:

1. Users should be strongly encouraged to use a happy path that maximizes security. Parameterized queries are that. SqlObject really encourages the user to uncritically "do the simplest thing"; SqlObject + StringTemplate puts you in a bad way.
2. Users should be strongly discouraged from using insecure tools. StringTemplate, when used as _all_ of the examples in the JDBI3 documentation indicate, is a highway to a pwned database.
3. Users should be made unmistakably aware that they are trading security for convenience. _Nowhere in the JDBI documentation is SQL injection even mentioned._

I'd like to know if I'm misunderstanding something...but my initial takeaway is that _this should not be used_ and I'm really concerned at what other gremlins I'm going to find in JDBI. Halp?

**Comment by eropple** [comment]
Hey, thanks for the fast response. I am _not_ actually aware of that. It'd be awesome if this is a documentation concern. Here's kind of where my brain went:

- The examples under [StringTemplate 4](http://jdbi.org/#_stringtemplate_4) all use `@Define` rather than `@Bind`.
- `@Define` is not actually...defined...in the JDBI3 documentation. It just pops up. Briefly in the mention of `@SqlScript` (which I never noticed, because I use Flyway), and then again in the documentation around `@UseStringTemplateSqlLocator`.
- This confusion was amplified by reading elsewhere in the documentation that by compiling with Java parameter names that `@Bind` would automagically work. I received errors complaining about a lack of `@Bind` annotations, however, when I switched to StringTemplate. Maybe it doesn't do automagic wireup? Or maybe it's a Kotlin problem, even though it worked without StringTemplate and I am compiling with Java parameter names.

StringTemplate may be totally fine, then--but I feel like this documentation is dangerously confusing, then. It may be worth having a critical eye passed over the documentation for best practices and for security, then. What, as a moderately security-conscious reader who is not a security or JDBC expert, I _really want to know_ at all times is "how can this break and screw me over", and it seems like the confluence of incomplete and security-agnostic documentation has led me down a bad path.

**Comment by eropple** [comment]
If nothing else, I would advise some **extremely bold statements** around "don't use `@Define` unless you know exactly what you're doing.

**Comment by qualidafial** [comment]
You're right that we could call out the SQL injection risk better. We had a section in there about SQL templating with a warning (and an xkcd link!), but it got commented out somehow prior to 3.0 release.

**Comment by qualidafial** [comment]
What would really help is if you could list those sections of the docs that need a warning.

**Comment by eropple** [comment]
I skimmed them, but there are feature gaps in my knowledge--I'm new to JDBI. If `@Define` is just a literal and `@Bind` does work everywhere, perhaps the best way to approach it is to remove it entirely from every example and have a small mention of it somewhere-or-other.

**Comment by TheRealMarnes** [comment]
I don't think we should be treating a feature as hostile or shameful, or removing examples of its use or anything. It just needs to be appropriately marked with its risks.  On that note, we do seem to be missing a section that explains templating as a feature in its own right instead of as a site node, merely an integration with another library.

But I feel like you've managed to walk through the manual in an unlikely, rare way to end up in the situation where you got. Most people won't ever stumble on this. `@Define` and `.define()` are both mentioned only half a dozen times, while the binding equivalents are shown 50 times each all over the place and have a dedicated section right at the top in `Core API/Arguments`. And of course `define` is mentioned all throughout the StringTemplate section... If that's the only part you read, then that's all you'll know about jdbi. I think it's a bit hasty to yell fire and bloody murder when you've skimmed past 90% of the manual.

I won't ever say no doc improvements of course, I'd just like to keep things in perspective. The manual could use some polishing but it's not like it absolutely gives you no clue at all about binding arguments or that it misleads you into thinking `defining` is the main way to use arguments.

**Comment by eropple** [comment]
I mean, you can tell me I'm weird or whatever to minimize it, but I kinda doubt it's that odd of a take when `@Define` is literally not mentioned anywhere else except in the StringTemplate section. "Hey, I just assume this works differently because it's under 'Third Party Stuff'" is generally not an unusual take. Impedance mismatches are normal and to be expected. It's tech. It's all half-broken duct-taped plumbing. I don't think this fails a reasonable-person test.

And, tbh, I _do_ kinda think that maybe it's worth meditating on whether literalizing SQL in TYOOL 2018 is something that should not be considered hostile. The overwhelming majority of input from anywhere is probably best considered hostile or at least probably mistaken. Including your own code.

But I'm going to be honest: after that neg in that last post, I'm just gonna smile and bow out and let y'all do what you will with user feedback. Thanks for the prompt responses, but that's a look I'm not really into.

**Comment by TheRealMarnes** [comment]
> you can tell me I'm weird or whatever

I didn't. Your path through the dev guide was just unusual (since you found Define but not Bind) and too short, as you were aware yourself. The fact that Define is barely mentioned, and only in the context of StringTemplate, should really drive home the point that it isn't to be used much; and mentioning it as little as possible is what you said we should do.

Yes, Defining shouldn't be done lightly, it should be well known to the jdbi user that it's a dangerous thing with uncontrolled inputs, but it's there in the first place because there's demand for it, valid usecases, so I don't think it should be treated as the black sheep in the herd.

>  "Hey, I just assume this works differently because it's under 'Third Party Stuff'" is generally not an unusual take.

Ok, I think I get what you're saying this time. You were reading about StringTemplate integration, and noticed that this section shows parameterization but uses a different mechanism for it than the rest of the guide, so your understandable assumption was that Defining is the equivalent of Binding when working in a StringTemplate context, like a sort of compatibility layer between libraries where Binding doesn't work.

I can see how that would confuse new users without a note to point it out, especially given the lack of a section about Defining as a standalone feature.

I'm not sure what you're getting defensive about. You come to us with a concern and feedback, but also with a correct remark that your knowledge of jdbi is limited and that you may have misunderstood things, painted a bit of a boogeyman over jdbi's actual face. I just clarified the things you did misunderstand, put your experience into perspective with that knowledge, and now we have a clearer picture already of how there can be 2 different interpretations of the same thing. This is nice progress, thanks for coming to us with it.

I was hoping to do some work on jdbi this weekend, might take this up as one of the first things tomorrow since doc changes should be easy to get through. Like @qualidafial asked, now that you know some more things again, do you see any other concrete changes that could be made to improve the situation?

**Comment by qualidafial** [comment]
I think the main reason that the StringTemplate section dwells on `@Define` is that defined attributes the primary input to the template engine. Bound parameters are orthogonal, and only come into play after the template engine has rendered the SQL from the template.

This is personal taste, but I would probably steer your toward the Freemarker template engine rather than StringTemplate, as the ST project appears to have been abandoned.

**Comment by stevenschlansker** [comment]
apparently it's not quite dead yet :O
https://github.com/antlr/stringtemplate4/pull/195
