### ISSUE TITLE
Feature Request: Cache Management

### ISSUE THREAD

**Issue by iq-dot** [jdbi/jdbi#134]
Hi Guys,

I'd like to throw in a feature suggestion, similar to some other DB libraries, I think it would be great if we could have a cache manager or adapter that we can specify with annotations and the JDBI library internally does the cache management of the queries.

Would be a great addition.

**Comment by qualidafial** [comment]
:-1: Lack of cache in JDBI is a *feature*.

**Comment by stevenschlansker** [comment]
Thanks for the suggestion.  I think qualidafial is right, if you want intelligent caching features, you will likely be happier with a full on ORM like Hibernate or OpenJPA.

If you want a caching solution with JDBI, I would consider building it as a module on top of JDBI rather than in core first.  If such a proof of concept turns out to be elegant and there's user demand, we could consider it as an addon module.  The chances of this being in core are very low though, sorry.

**Comment by miere** [comment]
Hi guys, I would like to suggest a different approach at this discussion and I'd like to hear your honest feedback about it...

I was reading [this](https://groups.google.com/forum/#!topic/jdbi/T-4ewxr5Bvc) topic before came here. And, I agree with you guys that support cache layers are totally application dependent. But, I would like to set a point here: _support cache layers would be hard to maintain in the long term, but allow developers to cache its queries isn't that hard_.

Let's imagine that, instead of providing a cache abstraction, JDBI could provide a way to "intercept" queries. Bellow is my suggestion:

```java
// Here an interface that could be provided by JDBI core module.
public interface QueryInterceptor {
  // ExecutableMethod could be a wrapper to the java.lang.reflect.Method and the DAO implementation
  // Another approach to this method would be store the arguments and the query into the ExecutableMethod too...
  Object interceptQuery( ExecutableMethod daoMethod, String query, Object[] args );
}

// at some place on your code, you can attach the query interceptor into the Handler
handler.attachQueryInterceptor( new MyQueryInterceptor() );

// Here a valid implementation that does nothing but call the query
public class MyQueryInterceptor {

  public Object interceptQuery( ExecutableMethod daoMethod, String query, Object[] args ) {
    return daoMethod.invoke( args );
  }
}

// Developers whom intend to cache their queries could create their own algorithm
// Bellow a non-thread-safe sample code just to make my point
public class CachedQueries {

  final Map<CacheEntry, List<Object> cachedData = new HashMap<>();

  public Object interceptQuery( ExecutableMethod daoMethod, String query, Object[] args ) {
    final CacheEntry entry = new CacheEntry( query, args );

    Object resultObject = cachedData.get( entry );
    if ( resultObject == null ) {
      resultObject = daoMethod.invoke( args );
      cachedData.put( entry, resultObject );
    }

    return resultObject;
  }
}

// represents a cached entry
class CacheEntry {
  final String query;
  final Object[] args;

  // Implement here a constructor
  // Implement here a valid equals and hashCode methods
}
```

Of course, there is a huge room for improvement on my suggested design, but I just want to make a point: is it simple enough to be included on JDBI?

Regards

**Comment by qualidafial** [comment]
I think this is a step in the right direction, however I would rather target the Query API for interception rather than SQL Objects.

**Comment by qualidafial** [comment]
@miere Would you open a separate issue to discuss this addition?

**Comment by stevenschlansker** [comment]
@miere I believe this could be workable.  Especially with the new extensions API, we are happy to support projects (such as a cache) that exist outside of core.  If the caching layer becomes stable and popular enough we could then consider promoting it into the main build.

I agree that targeting the Query API makes more sense -- SqlObject will turn into the query API behind the scenes, so if you target the core API you kill two birds with one stone.

Maybe the first step is to take a look at the brand new extension API, and the query API, and determine exactly what hooks are necessary to allow the implementation?  We could then have a PR adding the needed hooks, and you can develop your caching solution out of repo.  Sound like a plan?

**Comment by miere** [comment]
Hi @qualidafial, thanks for the fast answer...
I just filed the issue #334 as you asked.

**Comment by miere** [comment]
@stevenschlansker @qualidafial 
I not sure if I'm aware about the Query API. Do you mind to send the documentation link, or an unit test, which I can become more familiar with it?

**Comment by stevenschlansker** [comment]
I guess it's referred to as the 'Fluent API' elsewhere -- it's the first example on http://jdbi.org/

**Comment by qualidafial** [comment]
Opened PR #455, which would open the door for users and third party vendors to implement their own caching.
