### ISSUE TITLE
Can't use postgres casting operator with hash prefix parser

### ISSUE THREAD

**Issue by toadzky** [jdbi/jdbi#1389]
A query with something like `#recordId::UUID` throws an error because it tries to convert the whole thing to a named parameter. I know it can be done with the cast function, but it would be nice to be able to use the operator.

**Comment by TheRealMarnes** [comment]
Like in #1387 , is escaping not an acceptable solution?

```
@Test
public void testEscapes() {
    parser = new HashPrefixSqlParser();
    ParsedSql parsed = parser.parse("select \\#recordId::UUID", ctx);
    assertThat(parsed.getSql()).isEqualTo("select #recordId::UUID");
}
```

**Comment by toadzky** [comment]
does that create a named parameter of `recordId` or does it put that in the parsed sql as a literal?

**Comment by TheRealMarnes** [comment]
It's a literal, that's what escaping is for

`System.out.println(parsed.getParameters());`
> ParsedParameters{positional=false, parameterNames=[]}

**Comment by toadzky** [comment]
yeah. this bug is that if i try to use a named parameter with the cast operator it includes the casting in the name of the parameter

**Comment by TheRealMarnes** [comment]
Aahh, now I get it.

```
@Test
public void testEscapes() {
    parser = new HashPrefixSqlParser();
    ParsedSql parsed = parser.parse("select \\##recordId::UUID", ctx);
    assertThat(parsed.getSql()).isEqualTo("select #?::UUID");
    System.out.println(parsed.getParameters());
}
```

> Expected :"select #?::UUID"
> Actual   :"select #?"

You want it to stop at the `::` so you can still use `recordId` as a parameter within the casting text. I would say inserting whitespace should do that, but I'd agree that's not a good solution.

Mayhaps we can change the parsers interpret parentheses around variable names, so you could write it as `select \\#:(recordId)::UUID`?

**Comment by toadzky** [comment]
i knew the colon parser handled the casting stuff just fine, but i was using the hash one in the hopes it would handle the postgres slices better than the colon one.

**Comment by TheRealMarnes** [comment]
Mhm. Sad thing is both colons and hashes are apparently used for special operations in postgres.

I actually added a dollar prefix parser in a private branch, because I like `$foo` syntax, but also because I kind of expected exactly this sort of thing to happen one day. Would adding that to jdbi be a solution? I kind of like the number 3 for alternatives: there's a chance someone might need an alternative to nr 1, and there's a very slim chance someone needs an alternative for both nr 1 and nr 2. Odds that you'd need an alternative to nr 3 as well start getting astronomical.

**Comment by TheRealMarnes** [comment]
Oh, you know you can override the used parser for an individual query alone, right? `@UseSqlParser`

Just thinking about unblocking your code issue in parallel with a more structural solution.

**Comment by toadzky** [comment]
i rewrote my code to not need casting (just used string columns instead of UUID). i actually like the `$` prefix too, so having another alternate parser sounds good to me. i am using the annotation to override the colon parser for the one query where i needed it

**Comment by TheRealMarnes** [comment]
Sounds like you can keep using nice uuid columns instead of converting them to string columns, since you're gonna override the parser for this query, no?

Could you check out the PR I linked, see if you have any feedback on it, please? I might also make one for the dollar sql parser. Not promising these will be merged, just showing it's possible.

**Comment by toadzky** [comment]
i like it. i think it's a clean way to provide the capabilities and keep it simple at the same time

**Comment by hgschmie** [comment]
This works in current Jdbi. Added a unit test and closing the issue.
