### ISSUE TITLE
Improve/fix DefineBinds nullness detection

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1416]
Current `instanceof NullArgument` is rather fickle. ATM it doesn't work for some arguments, like `OptionalArgumentFactory` and `InputStreamArgument`. @stevenschlansker appears to be taking care of it for `ObjectArgument` in #1409.

Suggestion:
```
@FunctionalInterface
public interface Argument {
    /**
     * @return true if the value of this binding is null, false otherwise
     */
    default boolean isNull() {
        return false;
    }
}
```
Override in `NullArgument` with `return true` and in others with a `== null` on a value or whatever's appropriate. `OptionalArgumentFactory` for example would do `isEmpty()`. This is also more discoverable by argument implementors than a javadoc and manual comment, I think.

**Comment by stevenschlansker** [comment]
Also note that #1409 includes a fix to all the in-`core` issues here.  So it should only be a problem when interacting with custom code, not our own features.

**Comment by TheRealMarnes** [comment]
Do we agree then that `preventing > treating` but this is an exception due to very low expected use and we can just do a maintenance release in the near future? I can roll with that :+1:

**Comment by stevenschlansker** [comment]
I agree that it's unfortunate to have the feature not be more robust.  But I would rather live with the wart than introduce the wrong new API -- so we should make sure that we are solving actual use cases, rather than hypothesizing as to what a user *might* do.  Unless someone uses this feature and runs into the issue, they're not likely to even know to retrofit their custom arguments to override the new default method.

**Comment by TheRealMarnes** [comment]
I think `core` provably having an unintended incompatibility with itself goes a bit beyond mere hypothesizing. It's a clear bug we can expect people to run into as much as we can expect them to use `defineBinds`.

But I can agree with the rest you said.

**Comment by stevenschlansker** [comment]
As I said, once the PR linked above lands, all `core` arguments should behave inappropriately.

Also consider: we may be able to fix this issue without introducing new API, for example the `DefineNamedBindings` could supply a fake `PreparedStatement` to the binders and simply record whether `setNull` versus `setSomethingElse` (or nothing) is called.

**Comment by TheRealMarnes** [comment]
That's great. After the PR we should double-check that then. This issue is just for the record, to keep track of things in written form instead of memorizing and slacking everything.

And yeah, that sounds like an interesting idea. PreparedStatement is an interface IIRC so we could return a Proxy that records the calls like a sort of capture-replay thing.

**Comment by qualidafial** [comment]
I'm actually wondering if `@DefineNamedBindings` is worth the trouble.

`Argument` is a command interface. This means that `new NullArgument(Types.VARCHAR)` should be completely interchangeable with `(p, s, c) -> s.setNull(p, Types.VARCHAR)`.

It's a neat feature, but let's take a step back: we're going around the library, changing a bunch of factories to make sure that specifically return `NullArgument`--for the sake of an `instanceof` check, to support a _single_, dare I say niche, feature. Now we're considering adding a new method to `Argument` that has to be overridden everywhere for this feature to work.

Moreover, `Argument` is a `@FunctionalInterface`. I have a had time believing users will convert their existing arguments to classes just to satisfy this feature.

For these reasons I believe we should remove `@DefineNamedBindings`, until we can find a solution that doesn't have this weakness. It may have to wait for 4.x.

**Comment by stevenschlansker** [comment]
It's a really useful, though.  I'm a little frustrated that we keep conflating the feature that works today with the code we have with some ideal future feature that has a full understanding of nullness -- that it has to be perfect or nothing, and 'works for its intended purpose' doesn't seem to enter the equation.

I never asked us to extend argument factory with a new nullness API -- in fact, I recommended above leaving it with warts in just this feature, rather than rushing down that path.  I agree that moving away from the current functional interface is likely not the right path.

Can you suggest an alternate approach that solves my problem, if this feature is so odious as to necessitate removal already?

Currently I have in my code:

```java
@SqlQuery("insert into company (<if(id)>id,<endif>  name,  logo,  address,  status,    policy, createdAt, modifiedAt) "
        +             "values (<if(id)>:id,<endif> :name, :logo, :address, 'pending', <if(policy)>:policy<else>'{}'<endif>, now(),     now()) "
        + "on conflict (id) do update set "
        +     "<if(name)> name = :name, <endif> "
        +     "<if(logo)> logo = :logo, <endif> "
        +     "<if(address)> address = :address, <endif> "
        +     "<if(status)> status = :status, <endif> "
        +     "<if(policy)> policy = :policy, <endif> "
        +     "modifiedAt = now() "
        + "returning *")
@DefineNamedBindings
Company update(@BindPojo CompanyPatch company);
```

I've trimmed out some fields, but hopefully you can see how this is removing a fair amount of code I would otherwise have to write.  As things stand today, you'd have to `@Define` each optional property as a separate boolean.  This causes a ton of repetition both to redundantly declare, and then redundantly provide each property.  It's also less secure, as you'd end up binding the object's `toString` for every define, unlike this implementation that simply binds a `boolean`.

One possible alternate approach is to have parallel `@DefinePojo` but I'm concerned that now we have to start making parallel `@Define*` for every `@Bind*` strategy.  The current `@DefineNamedBindings` fills this need well.  What I want -- a boolean flag telling me about the presence of each bound property -- regardless of what bean or pojo or custom `@BindSomething` -- is exactly what I get.

I'm happy to look at other approaches as well but I hope you appreciate how this is solving my use case really nicely, and I'm not seeing a great path forward if this feature is removed.

**Comment by qualidafial** [comment]
If using the proxy approach we can localize this to `defineNamedBindings()` and not have it infect implementation details through the rest of the API, I can live with that.
