### ISSUE TITLE
test: Nondeterminstic `TestTimestampted` test failures

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1422]
Observed in Travis build https://travis-ci.org/jdbi/jdbi/jobs/481605774

```
[ERROR] Failures: 
[ERROR]   TestTimestamped.shouldAllowCustomTimestampParameter:88 
Expecting:
 <2019-01-19T01:49:50.767+02:00>
to be between:
 [2019-01-18T23:49:50.766Z, 2019-01-18T23:49:50.767Z]
```

I'm not sure exactly what's going on with this failure.

**Comment by TheRealMarnes** [comment]
I'm thinking the 3 `OffsetDateTime.now()` need to become `OffsetDateTime.now(OFFSET)` because the toString shows the timezones don't match, because the test asserts against `.now()` values which have the ever uncontrollable system timezone.

**Comment by stevenschlansker** [comment]
If that's the case, then how does the test ever succeed?

**Comment by TheRealMarnes** [comment]
I wonder that too...

**Comment by stevenschlansker** [comment]
I wonder if there's a difference in the nanosecond parts, but the `toString` only prints out to millis resolution.

**Comment by TheRealMarnes** [comment]
![image](https://user-images.githubusercontent.com/3950300/51419076-f7985000-1b87-11e9-9b0c-1f463a3b9dac.png)

🤔

**Comment by TheRealMarnes** [comment]
![image](https://user-images.githubusercontent.com/3950300/51419107-36c6a100-1b88-11e9-9a10-4e089bbba764.png)

Looks like if the Instant is the same, they're then ordered by offset, which puts the odt with offset +2 after the zulu ones.

So really the problem here is jenkins was too fast :p This test passes as long as there's a millisecond or more between the calls
