### ISSUE TITLE
LocalDate binding doesn't work when MySQL server has a different timezone to the client

### ISSUE THREAD

**Issue by sjprice** [jdbi/jdbi#1446]
I have a MySql server that is configured with a timezone of UTC. My Java app has a timezone of "Australia/Perth". When I save down `LocalDate` fields, they are stored in the DB as the previous day. Eg if I bind `2018-01-10` when I query the DB I see `2018-01-09`, *and* when I retrieve it using JDBI I get `2018-01-09`.

Here is a simplified example:
```
public interface ReportDao {

    @SqlUpdate("insert into report (report_date, title) values (:date, :title")
    void insert(@Bind("date") LocalDate date, @Bind("title") String title);

    @SqlQuery("select report_date from report")
    List<LocalDate> getAllDates();
}
```
And this is used as follows:
```
    // ...
    final ReportDao verdictDao = jdbi.onDemand(ReportDao.class);
    LocalDate d = LocalDate.of(2018, Month.JANUARY, 10);
    reportDao.insert(d, "bar");
    reportDao.getAllDates().forEach(System.out::println);
```
`2018-01-09` is printed, when I expect it to print out `2018-01-10`.

Client set-up:
* Timezone Australia/Perth
* jdbi v3.6.0
* mysql-connector-java v8.0.11  (using driver: com.mysql.cj.jdbc.Driver)

Server set-up:
* Timezone UTC
* MySQL 5.7.25-0ubuntu0.18.04.2
* Column type either DATE, or DATETIME

The problem occurs because the MySQL driver will convert the `java.sql.Date` from the client timezone to the server timezone. This seems like the correct thing to do, generally. Here is where JDBI interacts with the MySQL driver, in `JavaTimeArgumentFactory` line 29:
```
register(LocalDate.class, Types.DATE, (p, i, v) -> p.setDate(i, java.sql.Date.valueOf(v)));
```

And in the MySQL driver, in `ClientPreparedQueryBindings` (called from `ClientPreparedStatement`), we see this:
```
    // JDBI calls the 2-arg setDate()
    @Override
    public void setDate(int parameterIndex, Date x) {
        setDate(parameterIndex, x, this.session.getServerSession().getDefaultTimeZone());
    }

    @Override
    public void setDate(int parameterIndex, Date x, TimeZone tz) {
        if (x == null) {
            setNull(parameterIndex);
        } else {
            if (this.ddf == null) {
                this.ddf = new SimpleDateFormat("''yyyy-MM-dd''", Locale.US);
            }
            this.ddf.setTimeZone(tz);
            setValue(parameterIndex, this.ddf.format(x)); // TODO set MysqlType?
        }
    }
```

I've tested the above scenario with PostgreSQL and it doesn't suffer from the same issue.

I can think of 2 possible fixes for this in the JDBI source:

**1. Pin the time-zone by supplying a calendar to the setDate() call, in `JavaTimeArgumentFactory`**
```
// Calendar.getInstance() pins the client-side timezone thereby avoiding conversion
register(LocalDate.class, Types.DATE, (p, i, v) -> p.setDate(i, java.sql.Date.valueOf(v), Calendar.getInstance()));
```

**2. Supply an ISO date string instead of the date,  in `JavaTimeArgumentFactory`**
```
// Send the String to the DB, and allow the DB to coerce it into a date
register(LocalDate.class, Types.DATE, (p, i, v) -> p.setDate(i, v.toString()));
```

I've tested **1.** on both MySQL and Postgresql and it works. It is a bit horrible to create a calendar though. 

I haven't tested **2.** but it should work. Especially, given that both MySQL and Postgresql drivers format the date as a string before sending to the servers. **2.** is flaky though, as I'm pretty sure Oracle allows a date format to be set per session. So there's a good chance that this will not work in systems not using ISO formats.

Please let me know if you'd like more info!

**Comment by TheRealMarnes** [comment]
I've personally had woes like this before and tried to work them out, but that work has stalled a little... Kinda sad that this is still an issue today.

In a previous PR I considered adding a configurable javatime `Clock` to Jdbi's config precisely to get around this sort of thing, but it was reduced to only being used for `@Timestamped`. If we have to add anything, I'd rather add the modern `Clock` than shoving more legacy things like `Calendar` into it.

I feel like the first step we need to take here is writing a full test suite to test all the time types against all the biggest DBs specifically set up to have different timezones, and then work out a highlevel vision of how it ought to work (not just monkey-patch a few things).

**Comment by TheRealMarnes** [comment]
Sorry, wrong button

**Comment by TheRealMarnes** [comment]
I keep getting the feeling we really need to make more db-specific Plugins to handle datetime in a more tailored way for each db... Hsql for example doesn't do any of this, it just works with javatime objects without conversion. Then again, they're supposed to all work the same way through jdbc, so we shouldn't have to tailor anything.

One solution I have in mind that should give us the foundation we need to fix any of these issues is adding a `JavaTimeConfig` or similar where you can set a `Clock` to be used for all javatime mapping (or even for all time-related functionalities including `@Timestamped` since it's unlikely anyone wants jdbi to work with different Clocks at the same time).

There's an existing ticket for this ( #1271 ) that sprouted from my previous work, but I'm not sure the description even makes any sense anymore, I may have written it a bit too quickly to just serve as a reminder.

**Comment by sjprice** [comment]
> Then again, they're supposed to all work the same way through jdbc, so we shouldn't have to tailor anything.

Agreed. :) I think the problem stems from different DBs supporting different DATE types, eg Postgresql doesn't support DATETIME as a type, but MySQL does. Additionally, the JDBC spec can be a bit open for interpretation. 

For `LocalDate`, I think it does make sense to pass through a `Calendar`, eg:
```
(p, i, v) -> p.setDate(i, java.sql.Date.valueOf(v), Calendar.getInstance()));
```
The `p` here is a `PreparedStatement`, so we're stuck with `Calendar`. The only concern is that other JDBC drivers may not implement setDate(int, Date, Calendar) inline with MySQL & Postgresql.

**Comment by TheRealMarnes** [comment]
So anyway, to get back to the essence here... The only choice I really see is adding `Calendar.getInstance()` as you suggested. The question is, should we really? It would be in line with the rest of jdbi since we tend to assume system timezone, but it would override expected mysql behavior. Is it really up to us to change? It feels more like something users should override at their own discretion to me.

**Comment by stevenschlansker** [comment]
I'm very worried that changing the behavior here might break other database vendors, or other users that rely on the existing behavior.
`LocalDate` is a date without a timezone.  I'm really worried to continue to add timezone handling code for a datatype that inherently is timezone-less.

Could we instead consider passing the new `java.time` classes directly to the driver via `setObject`?  In the time since we shipped java 8 support, at least both MariaDB Connector/J https://github.com/MariaDB/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/BasePrepareStatement.java#L1253 and pgjdbc https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java#L545-L546 added support.

**Comment by TheRealMarnes** [comment]
@stevenschlansker Hsqldb supports that too. I actually have the work related to that on a branch right now, maybe we can make something more general of it? https://github.com/jdbi/jdbi/blob/25dc0edbeb85092030c9d8b1938fa5fdf49ff7d5/hsql/src/main/java/org/jdbi/v3/hsql/internal/GetObjectColumnMapperFactory.java

And yeah, LocalDate is timezoneless, but programs handling them must be aware of their own time management to handle them properly. The fact that we have to deal with them in the jdbc mapping logic makes them our problem.

What I can get behind though is saying "timezones are your own and your driver's problem if you use LocalDate, Jdbi makes no attempt to interpret anything aside from just getting something that runs". I think that's the currently implemented attitude since we just take the system timezone everywhere we need to deal with them.

**Comment by TheRealMarnes** [comment]
@stevenschlansker let's discuss #1449 to at least partially solve this

**Comment by sjprice** [comment]
> Could we instead consider passing the new java.time classes directly to the driver via setObject?

@stevenschlansker  Good idea, I just checked the MySQL diver source code, and they support it too. Here's the relevant chunk of code from `setObject`:
```
            } else if (parameterObj instanceof LocalDate) {
                setDate(parameterIndex, Date.valueOf((LocalDate) parameterObj));

            } else if (parameterObj instanceof LocalDateTime) {
                setTimestamp(parameterIndex, Timestamp.valueOf((LocalDateTime) parameterObj));

            } else if (parameterObj instanceof LocalTime) {
                setTime(parameterIndex, Time.valueOf((LocalTime) parameterObj));

            }
```

**Comment by sjprice** [comment]
@TheRealMarnes & @stevenschlansker - sadly the above code I pasted just invokes `setDate(int, Date)` and is therefore subject to the same timezone conversion. I went to raise a bug with MySQL, but discovered that it's a known issue: https://bugs.mysql.com/bug.php?id=93444

I hope they are as proactive as you :)

**Comment by stevenschlansker** [comment]
Well, at least they accept it as a bug.  Ideally, we'll push them to fix the driver bug, and then pass the `LocalDate` value through.  We may have to have a temporary fix here though depending on how long it takes them to get to a fix.

We can have a bugfix here since we already have our own strategy for binding `LocalDate` and we should support it properly -- but I look forward to the day when we can point at the vendor, "no, the bug is only in their code" ;)

**Comment by xak2000** [comment]
@stevenschlansker 
I don't see how this issue is fixed by #1449 ?

This issue about `DATE` column that is unintentionally changed by MySQL driver (Connector/J) when JVM timezone is different from MySQL server timezone.

And this bug is still reproduces with JDBI v3.12.0 and mysql-connector-java v8.0.19.

The bug is essentially in Mysql Connector. This is NOT JDBI bug. I created a [dedicated issue](https://bugs.mysql.com/bug.php?id=98436) for it. In essential they just violate `PreparedStatement.setDate` contract, that says:

> Sets the designated parameter to the given java.sql.Date value using the **default time zone of the virtual machine** that is running the application.

But they use MySQL server timezone instead of JVM timezone here. And this leads to this bug.

As I see by [other similar issue](https://bugs.mysql.com/bug.php?id=93444), these bugs are standing very long. So, I don't hope they will be fixed soon.

Maybe we can "fix" this bug on JDBI side? All we should do is to use `PreparedStatement.setDate` method with 3rd argument (Calendar) giving it default Calendar instance (that uses JVM timezone) instead of `PreparedStatement.setObject` for `LocalDate`. This is already default behavior when `setDate` is called without 3rd argument. And `setDate` without 3rd argument just delegates to `setDate` with 3rd argument `null`, and then wrong timezone is used in MySQL connector, but not in other connectors.

E.g. MariaDB uses [TimeZone.getDefault()](https://github.com/mariadb-corporation/mariadb-connector-j/blob/12d22ecc962e410d9c5f3bc2650fc43a7c8d1886/src/main/java/org/mariadb/jdbc/BasePrepareStatement.java#L426) and Postgres aslo uses [TimeZone.getDefault()](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java#L1017).

I think other connectors should use it too to be compliant with `PreparedStatement` interface contract.

But, honestly, I wish it fixed on MySQL Connector/J side...

**Comment by stevenschlansker** [comment]
The easiest workaround might be to use the new `java.time` types like `LocalDate` or `Instant`.
Those tend to have newer driver support without legacy bugs.  Does that work for your use case + with your server setup?

**Comment by xak2000** [comment]
@stevenschlansker The problem here that `LocalDate` is what this issue is actually about. :-)

This issue is about `LocalDate` from `java.time`. Not about old `java.util.Date` or even `java.sql.Date`.

Internally when you do `PreparedStatement.setObject` and pass an instance of `LocalDate`, Connector/J runs a big `switch` block of code, where, if "object" is instance of `LocalDate`, then it just executes `setDate` under the hood, converting passed `LocalDate` instance to `java.sql.Date` using `java.sql.Date.valueOf(...)`.

So, there is no magic here. Even if we use `LocalDate`, MySQL driver under the hood uses old good `java.sql.Date`... But it doing it in a wrong way. It uses Mysql Server timezone when it creates `SimpleDateFormat` instance:

```
this.ddf = TimeUtil.getSimpleDateFormat(this.ddf, "''yyyy-MM-dd''", cal, cal != null ? null : this.session.getServerSession().getDefaultTimeZone());
```

Then it formats `java.sql.Date` using this formatter:

```
setValue(parameterIndex, this.ddf.format(x), MysqlType.DATE);
```

And here is the problem. `SimpleDateFormat` doesn't understand that it formats `java.sql.Date` instance, that doesn't contain any timezone. It instead considers it like it `java.util.Date` (because unfortunately `java.sql.Date` extends it). And because of this, it interprets `YYYY-MM-DD` contained in `java.sql.Date` instance as timestamp (milliseconds from echo) in the JVM timezone. But, because formatter instance is created with MySQL Server timezone, the resulting `YYYY-MM-DD` string become shifted by several hours, and eventually by 1 day (because resulting string doesn't contain hours).

The workaround for this bug is to convert `LocalDate` to `java.sql.Date` on its own and then call `PreparedStatement.setDate` method instead of `PreparedStatement.setObject`. Important detail here is that when calling `PreparedStatement.setDate` a `Calendar` instance with JVM timezone should be passed. This way this line of code

```
this.ddf = TimeUtil.getSimpleDateFormat(this.ddf, "''yyyy-MM-dd''", cal, cal != null ? null : this.session.getServerSession().getDefaultTimeZone());
```

will not use MySQL Server timezone when creating `SimpleDateFormat` instance.

The only correct way to format `java.sql.Date` with `SimpleDateFormat` is to use JVM timezone in the formatter, because JVM timezone will be implicitly used internally by formatter as timezone of `java.sql.Date` (that doesn't contain any timezone actually).

P.S. The last comment of [this bug](https://bugs.mysql.com/bug.php?id=91112) statets that it should be fixed in next release of Connector/J. Finally! :-) Will see, if it is true.

**Comment by berniegp** [comment]
This is fixed in [MySQL Connector/J 8.0.20](https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-20.html) :

> When a Calendar was not used, a java.sql.Date value could not always be stored into and then retrieved from a MySQL server consistently. It was because Connector/J always converted a Date value to the server's time zone when storing it on the server as a MySQL DATE; but since a MySQL DATE does not have any time value, the hour, minute, and second parts of the original date was effectively lost. If the converted value is one day ahead of or behind the original value, when the value was retrieved through Connector/J and converted back to the local time zone, there was no time value for adjusting the date back to its original value, resulting in a one-day error. With this fix, any Date value is converted to MySQL DATE value using the JVM's time zone, so that the value is always consistent when being stored and then read back.

**Comment by stevenschlansker** [comment]
Praise be to the Flying Spaghetti Monster!  Would a MySQL / Jdbi user suffering LocalDate binding issues please confirm that time binding works well with the new driver? Thank you!

**Comment by jcoleman-scott** [comment]
I can confirm this solved the issue for me.

**Comment by visit-mental527** [comment]
@leaumar https://phps.space/questions/choose-the-date-in-the-database-that-is-closest-to-todays-date
