### ISSUE TITLE
bind List<Enum> to sql VARCHAR[] in kotlin

### ISSUE THREAD

**Issue by psartini** [jdbi/jdbi#1477]
Trying to bind a SQL Array of type VARCHAR[] with a List<Enum>.
I am not sure this should work at all, but #853 suggests it should.

My SqlObject method looks like this:
```
@SqlUpdate("INSERT INTO table (id, name, permissions) VALUES (:id, :name, :permissions)")
@GetGeneratedKeys
fun insert(id: UUID, name: String, permissions: List<Permission>): User
```

Insert code:
```
dao.insert(
   id = UUID.randomUUID(), 
   name = "name", 
   permissions = listOf(Permission.SOMEPERMISSION)
)
```

The error is somewhat misleading:
```
Missing named parameter 'permissions'.
...
...
, finder:[org.jdbi.v3.core.kotlin.internal.KotlinPropertyArguments@2c200f33]}
```

If I register the array type:
```
jdbi.registerArrayType(Permission::class.java, "varchar")
```

The error is still the same.
If I change the types to `Array<Permission>` like so:

```
@SqlUpdate("INSERT INTO table (id, name, permissions) VALUES (:id, :name, :permissions)")
@GetGeneratedKeys
fun insert(id: UUID, name: String, permissions: Array<Permission>): User
```

the error is gone.
Same is true for the ColumnMapper. But using Array<> in data classes would enforce us to override equals() and hashCode() in these classes - it would be much nicer to use List<>.

Plugins used:
PostgresPlugin()
KotlinPlugin()
SqlObjectPlugin()
KotlinSqlObjectPlugin()

**Comment by qualidafial** [comment]
In your first example, is `List<Permission>` a `java.util.List` or some Kotlin type?

**Comment by qualidafial** [comment]
Actually, I think I know the problem.

Mapping an existing `VARCHAR[]` into a `List<Permission>` should work because SQL array mapping exploits the column mapper registry. However, binding a `List<Permission>` to a `VARCHAR[]` won't work yet, because you don't have a correct SQL array type registered for `Permission`.

You tried to do this with `jdbi.registerArrayType(Class, String sqlTypeName)`, however that method is only valid for Java types directly supported by the JDBC driver (e.g. primitives, strings).

For other types, you have to provide a `SqlArrayType` implementation, which can adapt the type (`Permission`) into a different Java type which the JDBC driver supports (`String` in this case).

```java
jdbi.registerArrayType(Permission::class.java, SqlArrayType.of("varchar", { p -> p.name() }))
```

With all that said, I think it's reasonable to expect that enum arrays should be supported out of the box. We should register a `SqlArrayTypeFactory` for enums that respects the `Enums.enumStrategy` configuration property. (The Enums class hasn't been release yet)

**Comment by qualidafial** [comment]
@psartini See #1478

**Comment by qualidafial** [comment]
Will be fixed in 3.7.0

**Comment by psartini** [comment]
@qualidafial Thank you, that was fast.
I tried to register the enum type as pointed out by you - unfortunately it didn't work.

You asked about type of List<>, and indeed it seems there is another issue with kotlin Lists.
After switching to java.util.List<> , it worked.

I will create another issue.

**Comment by qualidafial** [comment]
@psartini Jdbi has a registry class `JdbiCollectors` which you can use to "teach" Jdbi how to create arbitrary collection types. Note that I'm using the term "collection" as a generic term here--not strictly `java.util.Collection`.

I wasn't aware that Kotlin has its own collection types. It would probably be pretty trivial to add support for Kotlin collections. Take a look at `GuavaPlugin` and `GuavaCollectors.Factory` for an example.
