### ISSUE TITLE
Postgresql jsonb operators

### ISSUE THREAD

**Issue by asakalou-exadel** [jdbi/jdbi#1510]
Hello Team, 

We need to query jsonb data using the @> operator.

Could you please let us know if there are any ways to that.
We need to perform queries like this:
```select * from entityName where jsonbPayload @> '{"status": :status}'```

And in java:
```
@SqlQuery("select * from entityName where jsonbPayload @> '{\"status\": \":status\"}'")
  List<EntityName> getEntityNameByStatus(@Bind("status") Status status);
```

Thanks!

**Comment by qualidafial** [comment]
What error do you get when you try it now?

Have you tried this in 3.7.0 or later?

**Comment by qualidafial** [comment]
I think I see the issue. JDBC doesn't recognize bound parameters inside a varchar literal, so Jdbi doesn't bother parsing named parameters in them.

The safest option would be to bind the whole JSON object as a parameter (i.e. as a `@Json Map<String, Object>`:

```
@SqlQuery("select * from entityName where jsonbPayload @> :properties")
List<EntityName> getEntityNameByProperties(
    @Bind("properties") @Json Map<String, Object> properties);
```

If `Status` is an enum, it might be safe to use varchar concatenation instead and just bind the status by itself:

```
@SqlQuery("select * from entityName where jsonbPayload @> CONCAT('{\"status\": \"', :status, '\"}')")
  List<EntityName> getEntityNameByStatus(@Bind("status") Status status);
```

Under normal circumstances I wouldn't recommend this approach since it can open you up to SQL injection attacks, but an enum should be safe.

**Comment by qualidafial** [comment]
Alternatively, you could use the `->>` operator to compare the `status` property directly:

```java
@SqlQuery("select * from entityName where jsonbPayload->>'status' = :status")
List<EntityName> getEntityNameByStatus(@Bind("status") Status status);
```

**Comment by qualidafial** [comment]
Closing as invalid. Feel free to follow up with further questions if you have them.

**Comment by asakalou** [comment]
Hello @qualidafial , thanks for you suggestions. ->> Does work for us!
