### ISSUE TITLE
JdbiCache needs some kind of expiry mechanism

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1528]
With #1525 merged in (which I love) we are now unfortunately possibly caching an unlimited number of parsed sql statements, which in principle may be dynamically generated.  See #93 / #125 for evidence that this does bite people.

**Comment by TheRealMarnes** [comment]
Size-limited and perhaps order-of-last-use-aware, or is there a different typical expiration we could go for? Would you want it configurable from an enum or pluggable with custom impl provided by a factory interface?

**Comment by qualidafial** [comment]
Size + LRU is a good start.

We might also (or alternatively) want the ability to disable specific caches. For apps with a very low cache hit rate, maintaining the cache will actually hurt performance.

**Comment by stevenschlansker** [comment]
While the entirety of the `caffeine` library is large and I'd prefer to avoid bringing it in, we might steal some of their code and ship our own stripped-down version.  In particular we could steal on of the smarter eviction policies like https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/adaptive/CarPolicy.java -- for example simple size + LRU has terrible worst-case performance and requires application tuning to work properly.

**Comment by ben-manes** [comment]
Do you need concurrency or is single-threaded okay? If a synchronized cache is fine then it should be simple to adapt any of those algorithms into a utility class. In that case then hill climbing w-tinylfu is still the best.

I assume you picked CAR because clock-based are more concurrency friendly. You could fork [CLHM](https://github.com/ben-manes/concurrentlinkedhashmap) to replace LRU, etc. That's kind of how Caffeine started, but many invasive changes due to Guava-style features and Map#compute methods. CLHM is pretty small and often gets embedded, but it was written for Java 5 and is only a concurrent lru map.

**Comment by qualidafial** [comment]
These caches are used from any number of threads, so we do need concurrency.

I'm experimenting with a _very_ naive least-recently-written using on read-write locks around a LinkedHashMap. I'm fairly certain I'm running afoul of some Java memory model rules of thumb.

So far I'm getting performance on par or better than ConcurrentHashMap. Which probably means I've overlooked something horrific in my implementation.

The more I look at concurrent collection code, the more I don't want to write one.

**Comment by ben-manes** [comment]
Please take a look at `ConcurrentLinkedHashMap` if you want a small concurrent LRU. It uses the same approach as Caffeine - record into a buffer, tryLock, and replay. This works quite well.

A `LinkedHashMap` with a rwlock will only work if insertion-order (fifo). In access-order (lru) it will corrupt itself because every read is a mutation of an internal linked list. This is warned in the JavaDoc and is why a making a classic LRU work concurrently was a hard problem.

I think there are primarily 3 strategies in use today: buffering, clock, or sampling. The tradeoff is that buffering is more complex to implement, but allows for more advanced algorithms. Clock and sampling are fast to read, but lower hit rates and Clock has worse write performance.

**Comment by qualidafial** [comment]
I may have given the wrong impression: we're looking for some reasonable cache eviction strategy. LRU was just my first thought. FIFO might also be a reasonable choice for our use case.

**Comment by qualidafial** [comment]
Just to frame the problem in terms of the current use case we are trying to solve: we recently introduced a caching mechanism with no expiration strategy.

This was reasonable for certain use cases in the library, e.g. loading SQL statements from resources on the classpath. This set of files is not likely to grow dynamically at runtime. We don't have any data yet to suggest this will be a problem for Jdbi users so we're calling an unbounded cache good enough for that use case.

However, we just recently got reports that parsing the same SQL operation repeatedly generated a lot of garbage on the heap from ANTLR. So now the SQL parser use that same, unbounded cache too. We are concerned that this might get folks into trouble (i.e. out of memory trouble), if their app is generating a lot of SQL dynamically at runtime--e.g. custom column lists in a select, or apps that create schemas per tenant and have to qualify every statement with the tenant schema name.

So what I think we need is an eviction strategy that is fast, rather than sophisticated. That's what got me thinking about using LinkedHashSet as a FIFO cache.

**Comment by ben-manes** [comment]
Thanks for the context. That makes sense so you have many simple options. A LHM as a fifo might be okay then, but it’s hard to know without data.

Anyway, wrt the original comment on Caffeine, CLHM is 115kb, LRU, and could be shrunk if embedded (e.g. ms-sql jdbc includes it). That would be a simple fallback option among your many choices to consider.

**Comment by stevenschlansker** [comment]
One request that I have is that the "no configuration" case should scale well to any reasonable number of statements N=10, N=100, N=1000
and it shouldn't behave terribly even when someone has huge MB-sized statements as in #1532 

This is a traditional weakness of LRU - if you have a 100 element cache and go through a 101-length cache access cycle, the hit rate falls to 0.

W-TinyLFU looks quite interesting as a possible way to sidestep this problem.

**Comment by ben-manes** [comment]
Unfortunately ARC/CAR doesn't handle this case very well ([glimpse](https://github.com/ben-manes/caffeine/wiki/Efficiency#glimpse)).

Adding TinyLFU is really trivial and could be easily hacked onto an LRU class. If you want something small and don't need `Map.compute` methods, it shouldn't be much work to port Caffeine's code back into CLHM. There's a fork in Groovy that added compute, so that might work as a baseline but I didn't review those changes so it would need a little testing. Depending on what you want it should be easy to stitch a couple things together.

**Comment by Hronom** [comment]
How we can disable default JdbiCaches here:
```
    public ConfigRegistry() {
        configs.put(JdbiCaches.class, new JdbiCaches());
    }
```

Here how we create `Jdbi`:
```
 Jdbi jdbi = Jdbi.create(
...
        );
        jdbi.installPlugin(new SqlObjectPlugin());
```

This thing kills our application with OOM.

Thanks!

**Comment by stevenschlansker** [comment]
Hi Eugene, when you OOM, which cache is too big?  We can add a way to disable it too if we cannot figure out a better fix.

**Comment by Hronom** [comment]
> Hi Eugene, when you OOM, which cache is too big? We can add a way to disable it too if we cannot figure out a better fix.

Hello, here what I have from heap dump:
```
One instance of "org.jdbi.v3.core.config.JdbiCaches" loaded by "sun.misc.Launcher$AppClassLoader @ 0x83b3b2e8" occupies 1 964 631 120 (94,25 %) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentHashMap$Node[]" loaded by "<system class loader>".

Keywords
java.util.concurrent.ConcurrentHashMap$Node[]
org.jdbi.v3.core.config.JdbiCaches
sun.misc.Launcher$AppClassLoader @ 0x83b3b2e8
```

Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.util.concurrent.ConcurrentHashMap$Node[1048576] @ 0xcb300000 | 4 194 320 | 1 964 629 496
table java.util.concurrent.ConcurrentHashMap @ 0x8024b770 | 64 | 1 964 629 632
val java.util.concurrent.ConcurrentHashMap$Node @ 0x8033cfe8 | 32 | 1 964 629 664
[10] java.util.concurrent.ConcurrentHashMap$Node[16] @ 0x8033ccf0 | 80 | 1 964 631 040
table java.util.concurrent.ConcurrentHashMap @ 0x840439b8 | 64 | 1 964 631 104
caches org.jdbi.v3.core.config.JdbiCaches @ 0x840439a8 | 16 | 1 964 631 120
val java.util.concurrent.ConcurrentHashMap$Node @ 0x84043988 | 32 | 32
[5] java.util.concurrent.ConcurrentHashMap$Node[16] @ 0x840436f0 | 80 | 232
table java.util.concurrent.ConcurrentHashMap @ 0x840436b0 | 64 | 296
configs org.jdbi.v3.core.config.ConfigRegistry @ 0x84043688 | 24 | 336
config org.jdbi.v3.core.Jdbi @ 0x84043660 | 40 | 520

I think the problem is that we concatenate string with all variables and then push it in `org.jdbi.v3.core.Handle#createQuery`
I think `org.jdbi.v3.core.config.JdbiCaches` implementation assumes that you **always** use `bind` and `define`.

We will try to rewrite on usage of `bind` and `define`.

Also, we have some usage of `Batch`, but as far as I understand all queries in batch didn't go trough cache at all(I hope). Because queries in `Batch` can't use `bind` and `define` and we can't use predefined batch.

**Comment by stevenschlansker** [comment]
Yes, please always `bind` your query parameters.  Concatenating everything into a String is a security issue.  Doing so should also fix your query caching problems.

Why can't you use `PreparedBatch`?

**Comment by Hronom** [comment]
> Yes, please always `bind` your query parameters. Concatenating everything into a String is a security issue. Doing so should also fix your query caching problems.

Security issue not a case here, since values not comes from user side, input values generated within one application that works with this database and owns it.

What about this query:
```
select * from test where id in (<id>)
```
Ok, I use `bindList` here will it create problems for cache?

Since I see in values of cache next:
```
select * from test where id in (:__id_0,:__id_1,:__id_2,:__id_3,:__id_4,:__id_5,:__id_6,:__id_7,:__id_8,:__id_9,:__id_10,:__id_11,:__id_12,:__id_13,:__id_14,:__id_15,:__id_16,:__id_17,:__id_18)
```
What if I can have different variations of list from 1 to 100, all this entries reside in cache, like 100 entries?

> Why can't you use `PreparedBatch`?

I push queries in batch that have different `set` and `where` clauses set, will `PreparedBatch` handle this?

For example, I want to push next queries in batch:
```
update test set work = :work, time1 = :time1, time2 = :time2 where type1 is true and type2 is true
update test set work = :work, time3 = :time3 where type3 is true
update test set work = :work, time2 = :time2, time3 = :time3, time5 = :time5 where type2 is true and type3 and type5 is true
```

**Comment by stevenschlansker** [comment]
@Hronom, please feel free to comment on #1588, hopefully this issue will be fixed in the next release of jdbi.  Thanks @ben-manes!
