### ISSUE TITLE
Why is select as not working properly? (Postgres)

### ISSUE THREAD

**Issue by JuanDavid31** [jdbi/jdbi#1602]
When using the same query directly on postgres it just works as expected, camel case column is returned.

```
val sql = "SELECT PRO.c_id as \"idProblematica\" FROM PROBLEMATICA PRO "
val maps = it.createQuery(sql).mapToMap().list()
```

But when using JDBI the alias is being returned in lowercase.

**Comment by leaumar** [comment]
In `MapMappers.class`:
```
public MapMappers() {
  caseChange = CaseStrategy.LOCALE_LOWER;
}
```

Lowercasing is (unfortunately) the default, and this will only change in Jdbi 4 (if it does).

`jdbi.getConfig(MapMappers.class).setCaseChange(CaseStrategy.NOP);` to fix it.

**Comment by stevenschlansker** [comment]
Just as some context: this decision was made because database vendors historically took different approaches to case sensitivity (some case-sensitive, some case-preserving, some convert-to-uppercase...) and so the default is to lowercase everything so it behaves reasonably similarly across database vendors.

Unfortunately this means our default casing strategy does not necessarily match your database's behavior.
