### ISSUE TITLE
How do I upgrade BinderFactory when moving to JDBI3?

### ISSUE THREAD

**Issue by waymav** [jdbi/jdbi#1672]
I am looking at some older code (that I didn't write) and wondering how I can upgrade it to JDBI3. I saw another post which asks about BinderFactory but it didn't seem to have much value to me. The things which don't seem to exist anymore are `BindingAnnotation` `Binder` and `BinderFactory`
```
import org.skife.jdbi.v2.sqlobject.Binder;
import org.skife.jdbi.v2.sqlobject.BinderFactory;
import org.skife.jdbi.v2.sqlobject.BindingAnnotation;

@BindingAnnotation(LoadTypeBinder.LoadTypeBinderFactory.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.PARAMETER})
public @interface LoadTypeBinder {

    /**
     * Value.
     *
     * @return
     */
    String value() default "it";

    class LoadTypeBinderFactory implements BinderFactory {

        @Override
        public Binder build(Annotation annotation) {
            return (Binder<LoadTypeBinder, SolrDbDao.LoadType>)
                (q, bind, arg) -> q.bind(bind.value(), arg.value());
        }
    }
}
```

**Comment by leaumar** [comment]
I believe you'd be looking for `ArgumentFactory` then, the interface that takes a java object and binds an appropriate sql value for it to a query. But I can't quite tell from your sample code what it is you're trying to bind or how/when, so could you post an example case too?

**Comment by waymav** [comment]
Sure thanks for the fast response. Below is an example. I should note that before the upgrade that `@RegisterRowMapper` would have been `@RegisterMapper` I believe I made the right choice in changing that to be the RowMapper.

```
    /**
     * Get reservoir updates.
     *
     * @param loadType loadType
     * @param topRows  topRows
     * @return ResultIterator
     */
    @RegisterRowMapper(DefaultMapper.class)
    @SqlQuery("EXEC csn_solr.dbo.spReservoirExport "
            +
            " @import=:import_type, @topRows=:topRows")
    ResultIterator<Map<String, Object>> getResMiscUpdates(
            @LoadTypeBinder("import_type") LoadType loadType,
            @Bind("topRows") int topRows);
```

Calling this method
```
    @Override
    public ResultIterator<Map<String, Object>> getResMiscUpdates(LoadType loadType, int topRows) {
        Function<Object[], Object> func = args -> delegate.getResMiscUpdates(
                (LoadType) args[0],(Integer) args[1]);
        return (ResultIterator<Map<String, Object>>) retry(func, loadType, topRows);
    }
```

**Comment by leaumar** [comment]
Just as an aside, it's odd to use `@RegisterRowMapper` but then return `ResultIterator<Map<String, Object>>`. I'd instead expect to see a `ResultIterator<T>` where `T` is the same as what's mapped by your `RowMapper`. If `DefaultMapper` provides mappers for column datatypes like timestamps or something, it should be `@RegisterColumnMapper` and probably registered globally.
Jdbi maps sql values from columns to java types with columnmappers, and then can bundle all the mapped columns of 1 row into a larger entity with a row mapper (or you can skip the row mapping and return a `Map` of values for each row like you're doing now).

Ok, so part of my confusion was the poor name `LoadTypeBinder`. `BindLoadType` would have followed the binder pattern better.

Is `LoadType` an enum? Enums are supported out of the box and bound using their `name()` as value. You don't need to use a custom binder for it unless `LoadType` has a field like `code` or something that you want to use instead. In that case, you'd register a `LoadTypeArgumentFactory`, probably globally. In either case, you wouldn't need to annotate your method parameter, unless you want to rely on an explicit binding name rather than the parameter name to match the query, then you can specify `@Bind("loadType") LoadType foo`. Binding by ordinal is also supported out of the box with `@EnumByOrdinal`.
Please see the extensive dev guide and javadoc for details on any of the things I mentioned, and let us know if a puzzle piece is missing.

What your code may need to look like now:
```
@RegisterRowMapper(ResMiscUpdateMapper.class)
@SqlQuery("EXEC csn_solr.dbo.spReservoirExport @import=:import_type, @topRows=:topRows")
ResultIterator<ResMiscUpdate> getResMiscUpdates(@Bind("import_type") LoadType loadType, int topRows);
```

**Comment by leaumar** [comment]
Obligatory follow-up:
```java
enum LoadType {}

@Data
class ResMiscUpdate {
	private LoadType loadType;
}

class ResMiscUpdateMapper implements RowMapper<ResMiscUpdate> {
	@Override
	public ResMiscUpdate map(ResultSet rs, StatementContext ctx) throws SQLException {
                // loadType is mapped the same way it's bound if you use jdbi's default enum handling
                // otherwise you need a LoadTypeColumnMapper to match a LoadTypeArgument
		return new ResMiscUpdate().setLoadType(rs.getObject("import_type", LoadType.class));
	}
}
```

**Comment by leaumar** [comment]
Come to think of it, you may not need all that work with the `RowMapper` because you can simply register `new PojoMapper<>(ResMiscUpdate.class, "");` and rely on that.

I get lost in the possibilities myself sometimes :)

I really recommend thoroughly browsing the dev guide for a while. Jdbi automates away a lot of plumbing that feels like it should be automatable.

**Comment by waymav** [comment]
Thanks for the help, I got stuck because our project is a bit bogged down by dependency issues but will be using this in the future!
