### ISSUE TITLE
SqlLogger: How to create an executable SQL ?

### ISSUE THREAD

**Issue by albert-kam** [jdbi/jdbi#1708]
I'm currently on `jdbi3-postgres` and using `SqlLogger` to help me debugging.

This is my current `SqlLogger` implementation:

```
    new SqlLogger() {
    	@Override
    	public void logAfterExecution(StatementContext context) {
    			log.debug("\nsql: {},\n\tbindings: {}\n\ttook {}ms\n\n",
    				context.getRenderedSql(),
    				context.getBinding().toString(),
    				context.getElapsedTime(ChronoUnit.MILLIS)
    			);
    		}
    	}
    }
```

And the output is something like:

```
    2020-02-09 17:01:32.359 [main] DEBUG app.AppContext - 
    sql: SELECT t.id, t.action, t.created_at, created_by.id c_id, created_by.displayname c_displayname FROM input_checksheet_flow t JOIN t_user created_by on created_by.id = t.created_by_id WHERE t.input_checksheet_id = :input_checksheet_id ORDER BY t.id DESC, t.created_at DESC LIMIT 1,
    	bindings: {positional:{}, named:{input_checksheet_id:20}, finder:[]}
    	took 3ms
```

This is helpful, but still problematic if i were to expect a complete sql ready to execute in a sql client like psql in my case.

It would be helpful if i could just copy paste the binding-populated sql statement to my sql client without having to replace parameter names with values from `StatementContext::getBinding`, but i'm not sure how to achieve this without having to do this manually, having to provide quotes for string upon replacement, etc. 

Perhaps there's a hidden gem within jdbi SqlLogger that i'm not aware about ?

**Comment by leaumar** [comment]
Libraries like jdbi interface with jdbc and bind parameter objects to jdbc query objects. The line ends there for jdbi. If you want the raw final sql without abstract data like param bindings as executed by the db, that's only visible within a db driver or some deep area of jdbc. Jdbi can't help you there. Db drivers themselves typically have logging facilities for this reason.

**Comment by stevenschlansker** [comment]
Yeah, unfortunately "copying out a ready-to-execute statement" simply isn't a feature we've implemented.
The JDBC driver allows many types of data transfer - notably binary data - and while the JDBC driver and PSQL utility speak a common protocol (the postgres server protocol) that is not the same thing as both speaking "what you type on the command line" PSQL SQL dialect.
You can find further information on this server protocol and see just how different it is here: https://www.postgresql.org/docs/11/protocol.html

I think it would be possible to implement a JDBC driver that instead of speaking the Postgres wire protocol, emits PSQL-like statements.  But that's a pretty big project and not really something Jdbi is targeting in the near term.  Sorry this use case isn't really possible today - I'm going to close this issue as "not really feasible" but happy to continue discussing it here or re-open if a PoC proves it's possible.
