### ISSUE TITLE
Update Oracle drivers to latest from Maven central

### ISSUE THREAD

**Issue by aalmiray** [jdbi/jdbi#1771]
The Oracle JDBC drivers are now available directly from Maven Central, starting with version `19.3.0.0`. The latest release as of September 2020 is `19.7.0.0`. More information can be found at https://www.oracle.com/database/technologies/maven-central-guide.html

Perhaps the `jdbi/jdbi3-oracle12` repository can be brought back into core and be renamed to `jdbi3-oracle`?

**Comment by stoyants** [comment]
Hi @stevenschlansker,

Don't you thing that if issues #2664 get closed this one can be closed as well?

The only difference than suggestion here is that I kept the original module name "jdbi3-oracle12" instead of just "jdbi3-oracle".
In fact I also like the clean name more, but then we should get rid of version 12 also from the package names and this will not be backward compatible.

Best Regards,
Stoyan

**Comment by stevenschlansker** [comment]
Yes, I agree, the driver is now up to date. Thanks for looking into this.
I am open to removing the `12` from the name, although that would potentially be disruptive to users who depend on the artifact, so I'm leaning towards just leaving it. Regardless, if anyone wants to open that discussion, please open a new issue.

**Comment by aalmiray** [comment]
Yes, keep the current name for backward compatibility but also offer the new name to start the migration. right now both artifacts will match in content. Later on they might differ.
