### ISSUE TITLE
 StatementBuilder isn't used by PreparedBatch and Batch.

### ISSUE THREAD

**Issue by fdimuccio** [jdbi/jdbi#178]
Hi, as title says, org.skife.jdbi.v2.PreparedBatch and org.skife.jdbi.v2.Batch do not use the StatementBuilder to create the statements, is it done by design or is it a defect?

I'm opening this issue because we implemented a custom statement builder to change flags on the  java.sql.Connection of the statement before creating it, but in case of batch statements those flags are not set since the builder is not used.

**Comment by stevenschlansker** [comment]
Looking at the code a bit, I suspect this is because the `StatementBuilder` expects to have a single `String` as the query, and does not handle the `List<String>` which is the `Batch`.

I suspect this is an artifact of the original design.  If this is important to you to change, and you can come up with a clean way to fix it without breaking compatibility, we would definitely consider the change.

**Comment by stevenschlansker** [comment]
fix in #613
