### ISSUE TITLE
Document the need for escaping the < operator

### ISSUE THREAD

**Issue by mrjoelkemp** [jdbi/jdbi#1814]
Refs https://github.com/jdbi/jdbi/issues/1156

I had a query that was trying to use the <= operator for date checking. I kept getting stringtemplate null errors that would say that the query is not an expression (hinting that it had a syntax error). I still don't know why I need to escape the operator either: https://stackoverflow.com/questions/59236448/jdbi-version-3-stringtemplate-when-to-escape-characters is the closest I could find and it doesn't have an answer.

Where would be a good place to add documentation that you may need to escape the `<` operator if you're getting stringtemplate exceptions? Ideally it would be somewhere in the stringtemplate docs. I'm happy to add the documentation in a PR if you know where's the best place to put it.

**Comment by leaumar** [comment]
I'd say in the chapter that talks about creating queries, since that's when you need to be made aware of that gotcha.

I'm having issues spinning up my reproduction sandbox... Does this happen with a simple query like `jdbi.useHandle(h -> System.out.println(h.createQuery("select 1 <= 2").mapTo(boolean.class).one()));`, and do you need to have the StringTemplate module installed or not?
