### ISSUE TITLE
(bug report) .bindArray crashes for sqlite-jdbc

### ISSUE THREAD

**Issue by metamaker** [jdbi/jdbi#1995]
Hi folks,

Thank you for your effort on jdbi, it is my favorite database access library!

2nd thing is that I encountered a problem with jdbi today due to createArrayOf not being implemented in sqlite-jdbc.

https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc4/JDBC4Connection.java#L105
https://github.com/jdbi/jdbi/blob/0420cc462f98565062bd577cf5d3a4d92a621060/core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java#L42

Application simply crashes when I use .bindArray() method with null pointer exception.

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at org.jdbi.v3.core.array.SqlArrayArgument.apply(SqlArrayArgument.java:43)
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:120)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:68)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1779)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:64)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:228)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:284)

```

Is there any chance to fix it?

I also ressurected relevant ticket in jdbc sqlite repo:  https://github.com/xerial/sqlite-jdbc/issues/415

**Comment by stevenschlansker** [comment]
Hi @metamaker , thanks for reporting this. The right fix is for SQLite to implement the JDBC interface as it promises to, although I appreciate as an end-user that's not a very satisfying answer.

In the meantime, one thing you could try is to configure the `SqlArrayArgumentStrategy`. This would cause Jdbi to call `jdbc.setObject(pos, new Object[] { ... })` rather than `createArrayOf`, which works better for some other drivers (H2). I am not sure it will work with SQLite but it's something to try.

When you set up your `Jdbi` instance, call:
```
jdbi.setSqlArrayArgumentStrategy(SqlArrayArgumentStrategy.OBJECT_ARRAY);
```

If this works, we can add a driver hint to always use `Object[]` arrays rather than `java.sql.Array` for the SQLite driver, and then you wouldn't have to do any customization.

**Comment by metamaker** [comment]
Hi @stevenschlansker! Thank you for the suggestions!

1. I was able to solve the issue by using `.bindList()`. 

Actually, you have a good example in documentation for IN clause with which I have had a problem:

```
handle.createQuery("SELECT value FROM items WHERE kind in (<listOfKinds>)")
      .bindList("listOfKinds", keys)
      .mapTo(String.class)
      .list();
```

2. [SQLite doesn't natively support array type](https://stackoverflow.com/a/3006302/2678487), I was doing a wrong thing trying to use this functionality.

I agree that the right fix is for SQLite to implement the JDBC interface as it promises to and, perhaps, throw an exception with meaningful description instead of dying quietly ([like MariaDB connector does](https://github.com/mariadb-corporation/mariadb-connector-j/blob/c3ccb9fb57cb0b33b31650714cd2689b34efa524/src/main/java/org/mariadb/jdbc/Connection.java#L692)). Then, this ticket can be closed, at very least the possible solutions are outlined. ;)
