### ISSUE TITLE
Binding map with List - >No type parameters found for erased type 'class java.util.Arrays$ArrayList[E]' with qualifiers '[]'

### ISSUE THREAD

**Issue by urkl** [jdbi/jdbi#2014]
Hi.

We have a native query ` SELECT * FROM TABLE WHERE field_a LIKE :field_a   AND field_b IN ( :field_b )` .

Our binder is based on Map.
So we are using bindMap() for binding parameters. 

:field_a is some string and :field_b is a List of Strings.

After binding we have this error:
No type parameters found for erased type 'class java.util.Arrays$ArrayList[E]' with qualifiers '[]'

What are we missing?

**Comment by stevenschlansker** [comment]
Hi @urkl , this is a side-effect of type erasure. Since `Map<String, Object>` has no information about the type of values, Jdbi only knows to bind `Object`. So it looks at the runtime type of the value, which in this case is `List` (with no type parameterization). So it cannot figure out how to bind the individual list elements.

The best solution is to declare Java types that map to your database records and not use the `Map` mapping. It might be possible to improve the Map "guessing" logic to handle this particular case, but you'll continue to run into rough edges where Jdbi cannot figure out the static type of values, and errors out.

**Comment by urkl** [comment]
I just can't use anything else than map in this project. This is basically why I checked Jdbi. Is there a way to create own argument mapper, the case is really only list. We have a lot of large tables with changing structures so objects are not an option.
Thanks for reply..

**Comment by stevenschlansker** [comment]
Hi @urkl , yes, you could write a custom argument mapper that handles your case exactly as you like. It's hard for us to include one generically in Jdbi that handles all the possible cases, but since you know exactly what you need, it shouldn't be too hard. Feel free to use the code in Jdbi as a starting point and ask more questions if you get stuck.
