### ISSUE TITLE
incorrect boolean type mapping

### ISSUE THREAD

**Issue by SimpleExpress** [jdbi/jdbi#2083]
version: 3.32.0
desc: 
I have a boolean type column is_view e.g., it will return as 1/0 to indicates true/false. 

| table_name | is_view  |
| ------------- | --- |
| abc | 1 |
| def | 0 |

when i try to map the result to a bean (`handle.createQuery(xxx).mapToBean(Table.class)`), if the field declared as boolean, then this field will always be false. 
```
import lombok.Data;

@Data
public class Table {
  private String tableName;
  private boolean isView;
}
```

on the other hand, if i declare it as Boolean, the result is correct.
```
import lombok.Data;

@Data
public class Table {
  private String tableName;
  private Boolean isView;
}
```

**Comment by hgschmie** [comment]
Hi @SimpleExpress, thank you for opening an issue here. Would it be possible to provide a test case. Mapping columns onto data is highly dependent on the column mappers registered.

**Comment by hgschmie** [comment]
So, this is not a JDBI problem. You ran into an issue with lombok:

If you use a Boolean object, this is what lombok creates:

```
 public java.lang.Boolean getIsView();
  public void setIsView(java.lang.Boolean);
```

but if you use a primitive boolean, lombok does this:

```
  public boolean isView();
  public void setView(boolean);
```

and JDBI behaves correctly, because the property for the first bean is called "isView" and for the second is called "view".  

The solution is to add a `lombok.config` file that contains

```
lombok.copyableAnnotations += org.jdbi.v3.core.mapper.reflect.ColumnName
```

and add a `@ColumnName("is_view")` on top of the "isView" field in your data class. Then both variants work correctly. I will add a unit test to the code base to demonstrate the correct use.
