### ISSUE TITLE
withHandle eats exceptions

### ISSUE THREAD

**Issue by bartkummel** [jdbi/jdbi#2100]
I'm using the `KotlinMapper`. When I make a mistake and e.g. the number of fields in my Kotlin data class does not match the number of fields in the result set, the `KotlinMapper` throws an exception which very nicely shows what's wrong. (Line 111 in `KotlinMapper.kt`, inside the `specialize0` function.) 

When I do this in a `withHandle` block, the exception is eaten by the `withHandle`. See `Jdbi.java`, line 355: there's a `try` with only a `finally`. I think you should add a `catch` clause there, that logs any exception on ERROR or WARNING level.

Here's an example to reproduce this:
```kotlin
    private fun findEvents(): List<Event> {
        return jdbi.withHandle<List<Event>, Exception> { handle ->
            logger.info("Querying for events...")

            val result = handle
                .createQuery(findEventsQuery)
                .mapTo<Event>()
                .list()
            logger.info("Found ${result.size} events.")
            result
        }
    }
```
Make sure that the `Event` data class has an error, so it does not match the fields of the result set of the query. Notice that the code runs fine, returning 0 results, not throwing an exception and not logging anything.

**Comment by hgschmie** [comment]
hey @bartkummel! Thank you for opening an issue with JDBI. I will look into this, but I am not a real kotlin expert, so it may take a bit.

**Comment by bartkummel** [comment]
Thanks for you reply, @hgschmie ! I write Kotlin on a daily basis. Let me know if I can be of any help with Kotlin-specific stuff.

**Comment by Proximyst** [comment]
@bartkummel Hi!  This issue caught my attention, so I hope I'm not stepping on any toes with doing the investigation here.

I've tried reproducing this bug, but I can't really seem to figure out how you've ran into this problem.

## Simple test cases

I've written a test case in [`KotlinPluginTest`](https://github.com/jdbi/jdbi/blob/ee2270d759c78a4bb6ac29a659288b272e88feab/kotlin/src/test/kotlin/org/jdbi/v3/core/kotlin/KotlinPluginTest.kt) (it was convenient...) to try to figure it out:

```kotlin
    @Test
    fun testWithHandle() {
        h2Extension.jdbi.withHandle<List<Unit>, Exception> { handle ->
            throw Exception("Testing")
        }
    }
```

which fails due to the exception being properly propagated.

Even if you specify the wrong exception type (i.e. one that your thrown exception is _not_ an instance of):

```kotlin
    @Test
    fun testWithHandle() {
        h2Extension.jdbi.withHandle<List<Unit>, RuntimeException> { handle ->
            throw Exception("Testing")
        }
    }
```

the test case fails, because the exception was propagated properly.

For clarity, the logged exception for both of these cases:

```
java.lang.Exception: Testing
	at org.jdbi.v3.core.kotlin.KotlinPluginTest.testWithHandle$lambda-1(KotlinPluginTest.kt:69)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:357)
	at org.jdbi.v3.core.kotlin.KotlinPluginTest.testWithHandle(KotlinPluginTest.kt:68)
	[junit call stack omitted]
```

So the `withHandle` is not the problem (nor could it be; see below).

### Why the simple test cases make sense

I'm fairly sure you're calling this method, though I cannot be sure as you didn't link a specific tag or source code: https://github.com/jdbi/jdbi/blob/ee2270d759c78a4bb6ac29a659288b272e88feab/core/src/main/java/org/jdbi/v3/core/Jdbi.java#L350-L361

The definition for the delegate method, `HandleCallback#withHandle` is as follows: https://github.com/jdbi/jdbi/blob/ee2270d759c78a4bb6ac29a659288b272e88feab/core/src/main/java/org/jdbi/v3/core/HandleCallback.java#L30

Therefore it should simply propagate the exception up the chain, making the try statement equivalent to this (ignoring the fact that this is not legal due to the `catch` referencing a type parameter):

```diff
         try (Handle h = this.open()) {
             threadHandleSupplier.set(new ConstantHandleSupplier(h));
             return callback.withHandle(h);
+        } catch (X ex) {
+            throw ex;
         } finally {
             threadHandleSupplier.remove();
         }
```

## A test case like the original issue

I've now modified it to actually select something into a `List` like you reported originally, with the query returning faulty data that cannot be mapped properly:

```kotlin
    @Test
    fun testWithHandle() {
        h2Extension.jdbi.withHandle<List<Thing>, Exception> { handle ->
            // Thing also requires the column `id` which I have omitted from the query.
            handle.createQuery("SELECT name FROM something")
                .mapTo<Thing>()
                .list()
        }
    }
```

which also threw an exception:

```
java.lang.IllegalArgumentException: Could not map Constructor-injected type 'Thing' with 6 parameters, only 2 parameter matched, 1 unmatched.
Available columns:    [name]
Matched parameters:   [parameter #1 name of fun <init>(kotlin.Int, kotlin.String, kotlin.String?, kotlin.String?, kotlin.String?, kotlin.String): org.jdbi.v3.core.kotlin.KotlinPluginTest.Thing, parameter #5 defaulted of fun <init>(kotlin.Int, kotlin.String, kotlin.String?, kotlin.String?, kotlin.String?, kotlin.String): org.jdbi.v3.core.kotlin.KotlinPluginTest.Thing]
Unmatched parameters: [parameter #0 id of fun <init>(kotlin.Int, kotlin.String, kotlin.String?, kotlin.String?, kotlin.String?, kotlin.String): org.jdbi.v3.core.kotlin.KotlinPluginTest.Thing]

	at org.jdbi.v3.core.kotlin.KotlinMapper.createSpecializedRowMapper(KotlinMapper.kt:126)
	at org.jdbi.v3.core.kotlin.KotlinMapper.specialize(KotlinMapper.kt:71)
	at org.jdbi.v3.core.result.ResultSetResultIterator.<init>(ResultSetResultIterator.java:38)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:57)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:240)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:296)
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:285)
	at org.jdbi.v3.core.kotlin.KotlinPluginTest.testWithHandle$lambda-1(KotlinPluginTest.kt:71)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:357)
	at org.jdbi.v3.core.kotlin.KotlinPluginTest.testWithHandle(KotlinPluginTest.kt:68)
	[junit call stack omitted]
```

**Comment by bartkummel** [comment]
Hi @Proximyst,

Thanks for looking into this! 

- I think I was wrong in pointing to the `try`/`finally`. Of course you are right that this doesn't prevent an Exception from being thrown. Should have come up with that myself.
- I tried to reproduce the problem in a unit test, like you did. I was not able to reproduce it either.
- However, in my production code, the problem still presists: if I change either the query or the data class, the code runs without throwing an exception.

I think the "eating" of the exception happens somewhere else then. Can still be JDBI or another DB-related library, but can also be somewhere else. I'll close the issue for now.
