### ISSUE TITLE
Easy mapping of beans using Jackson

### ISSUE THREAD

**Issue by dobesv** [jdbi/jdbi#213]
Jackson has very flexible object creation.  I made a little ResultSetMapper that uses Jackson to build beans.

See here:

https://gist.github.com/dobesv/0b47e853cde23d1870a8

**Comment by jhaber** [comment]
People looking for this feature can check out [Rosetta](https://github.com/HubSpot/Rosetta); it uses a binding annotation and mapper factory to achieve this

**Comment by stevenschlansker** [comment]
Very cool!  Do you think any sort of core integration makes sense here?  Or should we just leave Rosetta as a separate project that builds on JDBI?

**Comment by jhaber** [comment]
Implementation-wise, I the jDBI API has been flexible enough to support everything I've wanted to do so far.  From a discoverability perspective though, maybe jDBI should maintain a curated list of things built on top? (à la [Jackson](https://github.com/FasterXML/jackson#third-party-datatype-modules))

**Comment by stevenschlansker** [comment]
OK, so maybe the action item here is to add a link to Rosetta in the docs :smile:

**Comment by jhaber** [comment]
That would be great! I just spent some time cleaning up the docs. The main readme is [here](https://github.com/HubSpot/Rosetta/blob/master/README.md) and there's a longer list of advanced features [here](https://github.com/HubSpot/Rosetta/blob/master/FEATURES.md)

**Comment by dobesv** [comment]
Well if Rosetta works, then this issue is resolved!

**Comment by jhaber** [comment]
It works! We use it pretty extensively here at HubSpot, but we're always interested in getting feedback and making improvements :smile: Two Rosetta features we really like are the nested object support with dot-notation (makes it easy to bind/map complicated object graphs), and the `@StoredAsJson` annotation which lets you store an entire subobject in a single text or blob column. (For example, [these](https://github.com/HubSpot/Blazar/blob/v2/BlazarBase/src/main/java/com/hubspot/blazar/base/ModuleBuild.java#L34-L37) field store [this](https://github.com/HubSpot/Blazar/blob/f0863d145cdac2cb60bb6abfef31cc90095d8ba1/BlazarBase/src/main/java/com/hubspot/blazar/base/BuildConfig.java#L13-L18) complicated object, but rather than try to write a real schema, we just annotate these fields with `@StoredAsJson` and throw them into [these](https://github.com/HubSpot/Blazar/blob/f0863d145cdac2cb60bb6abfef31cc90095d8ba1/BlazarData/src/main/resources/schema.sql#L77-L78) text columns, which Rosetta [binds](https://github.com/HubSpot/Blazar/blob/f0863d145cdac2cb60bb6abfef31cc90095d8ba1/BlazarData/src/main/java/com/hubspot/blazar/data/dao/ModuleBuildDao.java#L50-L51) and [maps](https://github.com/HubSpot/Blazar/blob/f0863d145cdac2cb60bb6abfef31cc90095d8ba1/BlazarData/src/main/java/com/hubspot/blazar/data/dao/ModuleBuildDao.java#L18-L20) right out of the box)

**Comment by buremba** [comment]
Rosetta doesn't seem to support JDBI 3, any other alternatives?

**Comment by jhaber** [comment]
I started adding JDBI3 support in this PR: https://github.com/HubSpot/Rosetta/pull/60
Needs some more polish and testing but I definitely don't see any major hurdles (and additions like `SqlStatement#bindMap` actually make our lives a lot easier)

**Comment by qualidafial** [comment]
Please note that `bindBean()` supports nested property binding as of v3.
