### ISSUE TITLE
Returning Streams is no longer supported since 3.35.0

### ISSUE THREAD

**Issue by PhilippSchueler5648** [jdbi/jdbi#2255]
Due to performance reasons we decided to use Streams as return values for huge requests on our bigger database tables.

` 
   @SqlQuery(
        """
        SELECT v.OUID FROM VARIANT v
    """
    )
    @FetchSize(value = 10000)
    public fun findAllOuids(): Stream<String>
`

This is no longer possible to use since 3.35.0, because the Stream is already closed, when you try to access it. Is there a reason as to why this behavior was changed?

**Comment by stevenschlansker** [comment]
I don't believe this changed in Jdbi - when a transaction or handle is closed, your streams are invalid, and this has always been the case. Do you have a self-contained example that used to work and now does not?

The fix is to process the stream with the database transaction held open. You can explicitly manage an outer transaction, or use the new `findAll(Consumer<Stream<String>>)` style

**Comment by hgschmie** [comment]
There are a number of changes to resource management in 3.35.0.  This should still work (same as Iterator<>). I will take a look

**Comment by hgschmie** [comment]
are you using onDemand or withExtension/useExtension with your dao objects? Looking at your code, it looks like you are using Kotlin.

**Comment by PhilippSchueler5648** [comment]
Yes we are using onDemand with our DAO objects by initializing the bean within a factory like this:

`
    @Bean
    public fun futureSellingPriceDao(jdbi: Jdbi): FutureSellingPriceDao {
        return jdbi.onDemand(FutureSellingPriceDao::class.java)
    }
`

And also yes regarding the question about Kotlin.

**Comment by PhilippSchueler5648** [comment]
In regards to the question by @stevenschlansker 

Our applications basically consume a record from a Kafka topic, insert it into our database and forward that information, that is enriched by other information from our database. Therefore we have Systemtests, that use a locally hosted Kafka and a Postgres within a Testcontainers environment. Within our Github repository we have integrated Dependabot, which automatically upgrades our dependencies on a regular basis. It creates its own branch, upgrades a single dependency within that branch and merges the branch onto main, as soon as the pipeline is green. 
During the dependabot upgrade for JDBI v3.35.0 our Systemtests broke for some of our applications. We were able to determine, that those applications, that broke use a Stream within some of their DAO-functions. We were also able to see during debugging, that the Stream was closed prematurely. When we reverted the upgrade, the Stream was still open and the tests worked as intended.

**Comment by hgschmie** [comment]
Hi @PhilippSchueler5648,

So there is https://github.com/jdbi/jdbi/blob/master/sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestStream.java which obviously works (and passes unit tests). I will try to figure out onDemand.

**Comment by hgschmie** [comment]
yeah, it is a bug.

**Comment by hgschmie** [comment]
ok, so here are a few updates. 

This is the simplest fix and it probably works for you: replace `public fun findAllOuids(): Stream<String>` with `public fun findAllOuids(Consumer<Stream<String>> consumer)`  and modify your code to consume the callback

There are three ways in Jdbi on how to get a fully managed handle for a SqlObject:

- `jdbi.with/useExtension(DaoClass.class, dao -> { ... callback code })`. This is the most preferred way. You would inject the Jdbi into your code and then do `useExtension` or `withExtension` with a callback. In this case, there is a handle created at the beginning of the callback, then your code is executed, then the handle is closed at the end of the callback
- `handle.attach(DaoClass.class)`. Here, the handle is managed outside the dao class lifecycle. The handle lifecycle is managed outside the Dao, so the code does not do anything with it.
- `jdbi.onDemand(DaoClass.class)`. This is the trickiest one. Because there is not explicit callback, every method on the DaoClass is wrapped in its own little callback (within a Java proxy) that does "create handle, execute the method, close the handle". This works well except for things that need "live" resources outside the scope of a single method call. Such as `Iterator<T>`, `Stream<T>` and `ResultIterator<T>`. 

Why did that work before 3.35.0? Well, it did not. It actually leaked handle objects, statement context objects and ultimately PreparedStatement and ResultSet objects. One could get away with that because for most modern database drivers, these bjects are lightweight and they can be garbage collected even if they were not properly released and closed. 

In 3.35.0, we reworked the whole resource tracking logic and ensured that we free and close all resources that Jdbi implicitly allocates. It is the right thing to do. Unfortunately, this does affect `onDemand` with the three return types mentioned above because it closes the necessary resources now before you can consume them. 

This sucks, because it breaks existing code. However, there is not a good fix yet. I looked at various ways to "break open" the lifecycle but at a bare minimum you will end up with having to wrap the stream in a t-w-r construct (or the equivalent Kotlin thing that currently escapes my mind). Otherwise you will leak resources. In fact, your code that uses pre-3.35.0 Jdbi and onDemand streams leaks resources today. And what is the most annoying thing is that there is nothing you can do right now except upgrading and rewriting. 

I think there is a more comprehensive fix possible (that will restore pre-3.35.0 behavior so that existing code would continue to function) but it requires some refactoring on how we create the proxy objects.

**Comment by PhilippSchueler5648** [comment]
Thanks for the quick feedback. 

We already tried to extend our DAOs with Transactional, so that we could use useTransaction with a Callback. This solution had the negative side effect of being very tricky to Mock within UnitTests. 
Nevertheless I'll try out your suggested solutions and will return with the information about what works best for us.

**Comment by hgschmie** [comment]
Great to hear. While we definitely need to update the documentation, I will look a bit more into this to see what we could do code-wise.

**Comment by irineuruiz** [comment]
[jdbiIterator.zip](https://github.com/jdbi/jdbi/files/11019066/jdbiIterator.zip)

Hello,

We are facing a similar problem using Iterator with jdbi3 in a dropwizard application.

I put together a small scenario that works with version 3.34 of jdbi3 but fails with later versions.

I'm putting the zip with our example attached.

CREATE TABLE public.tb_person
(
id integer NOT NULL,
firstname text,
dt_insert timestamp with time zone,
CONSTRAINT pk00_tb_person PRIMARY KEY (id)
)
WITH (
OIDS=FALSE
);

**Comment by hgschmie** [comment]
Hi @irineuruiz. Thank you for the test scenario. I will check it out in the next few days.

**Comment by hgschmie** [comment]
while you probably would not believe the amount of change that this bug report has triggered, the actual outcome is now documented in http://jdbi.org/#using-steams-and-iterators with exact examples what works and what does not. The 3.38 release which contains all the changes will be going out this week.

**Comment by hgschmie** [comment]
@irineuruiz Your code uses the "return a cursor object from an on demand method", which does not work (the method closes the handle when it exists and while it gives you an iterator, it is no longer viable because it has closed the database connection.

If you really need to use an iterator, your best option is to manage the handle yourself (which is annoying because it would drag database code into the resource) or use a Consumer argument (which is a callback and then use a jersey streaming resource). 

See the http://jdbi.org/#_use_consumer_arguments chapter for more details on how to implement this.

**Comment by hgschmie** [comment]
Documentation will be in 3.38.0 It is understood that the behavior change is annoying, but the code never worked correctly before (it was always prone to leaking resource in some corner cases) and the changes in 3.35.0 actually fixed those.
