### ISSUE TITLE
Failing statements with @GetGeneratedKeys leaks cursors on Oracle

### ISSUE THREAD

**Issue by magnusr** [jdbi/jdbi#230]
An `SqlObject` method with `@GetGeneratedKeys` that fails during execution (resulting in an `UnableToExecuteStatementException`) leaks a cursor on Oracle. After enough failures, the connection runs out of cursors, rendering it useless. Adding a call to `close` in the `catch` clause that maps `SQLException` to `UnableToExecuteStatementException` in `SQLStatement.internalExecute` fixes it, but I'm unsure of the implications of doing that.

**Comment by magnusr** [comment]
[TestClose.txt](https://github.com/jdbi/jdbi/files/36594/TestClose.txt)

**Comment by magnusr** [comment]
[0001-Close-failing-statements.patch.txt](https://github.com/jdbi/jdbi/files/36595/0001-Close-failing-statements.patch.txt)

**Comment by magnusr** [comment]
[TestClose.java.txt](https://github.com/jdbi/jdbi/files/36596/TestClose.java.txt)

**Comment by stevenschlansker** [comment]
Thanks for reporting this @magnusr.  Next time feel free to submit as a PR rather than attached patch file, it would be much easier for us to see the changes and then you get credit for the commits if we merge it!  I've created #231 and #232 and assuming they pass code review your issue should be fixed in the next release.
