### ISSUE TITLE
Running mvn dependency:tree does not work out of the box

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#2532]
Looks like the dependency check plugin is skipped entirely by default.

```
code/jdbi3/docs% mvn -o dependency:tree
[INFO] ------------------------< org.jdbi:jdbi3-docs >-------------------------
[INFO] Building jdbi3 - internal - documentation 3.42.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.6.0:tree (default-cli) @ jdbi3-docs ---
[INFO] Skipping plugin execution
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.379 s
[INFO] Finished at: 2023-11-14T11:26:50-08:00
[INFO] ------------------------------------------------------------------------
```

It'd be nice for running `dependency:tree` to work out of the box.

**Comment by hgschmie** [comment]
This works everywhere, except in the doc module. :-) Is the doc module important for you? This is skipped by `basepom.check.skip-dependency` being set to true, otherwise the dependency checker will run as part of the build and the doc module has very messed up dependencies (because it pulls in every module to build the javadocs). We would need to split out the javadoc generation from the rest of the docs to fix that correctly and it seems it is not worth the effort.

for the doc module, run `mvn -Dbasepom.check.skip-dependency=false dependency:tree`

**Comment by stevenschlansker** [comment]
Ok, I guess this is fine. It just surprised me when I tried to debug the Guice aopalliance dependencies and felt broken.
