### ISSUE TITLE
Could not get OUT parameter from statement,  ORA-17009: Closed statement with version 3.43.0  

### ISSUE THREAD

**Issue by hjortling** [jdbi/jdbi#2592]
After migrating from org.jdbi:jdbi3-core:3.42.0 to org.jdbi:jdbi3-core:3.43.0 we are getting issues when doing stored procedure calls from a Spring Boot 3 application against an Oracle DB Version 19.19.0.0.0".

The implementation looks similar to this: 
```
public int fetchNumberOfPets_3_42_0() {
	        long start = System.nanoTime();
		try {
			OutParameters result = getJdbi().withHandle(handle ->
					handle.createCall("call pets.countPets(:x)")
							.registerOutParameter("x", Types.INTEGER)
							.invoke());
			return result.getInt("x");
		} finally {
			metrics.reportDBDelay(Duration.ofNanos(System.nanoTime() - start));
		}
	}
```
It worked fine with jdbi3-core:3.42.0 but it now with jdbi3-core:3.43.0 it throws the following exception

```
stack_trace	
j.sql.SQLException: ORA-17009: Closed statement
https://docs.oracle.com/error-help/db/ora-17009/
	at o.j.d.OracleClosedStatement.getInt(OracleClosedStatement.java:1722)
	at o.j.d.OracleCallableStatementWrapper.getInt(OracleCallableStatementWrapper.java:655)
	at c.z.h.p.HikariProxyCallableStatement.getInt(HikariProxyCallableStatement.java)
	at o.j.v.c.s.Call$OutParamArgument.map(Call.java:258)
	... 35 common frames omitted
Wrapped by: o.j.v.c.s.UnableToExecuteStatementException: Could not get OUT parameter from statement [statement:"call pets.countPets(:x)", arguments:{positional:{}, named:{x:org.jdbi.v3.core.statement.Call$OutParamArgument@65e7fd4d}, finder:[]}]
	at o.j.v.c.s.Call$OutParamArgument.map(Call.java:275)
	at o.j.v.c.s.Call$OutParamArgument.lambda$supplier$0(Call.java:234)
	at o.j.v.c.s.OutParameters$ParameterValueMap.getValue(OutParameters.java:553)
	at o.j.v.c.s.OutParameters.getObject(OutParameters.java:93)
	at o.j.v.c.s.OutParameters.getObject(OutParameters.java:68)
	at o.j.v.c.s.OutParameters.getNumber(OutParameters.java:490)
	at o.j.v.c.s.OutParameters.getInt(OutParameters.java:169)
	at c.s.w.u.e.m.r.DBRepository.fetchNumberOfPets_3_42_0(DBRepository.java:159)
	at j.i.r.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at j.l.reflect.Method.invoke(Method.java:580)
	at o.s.a.s.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	at o.s.a.f.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at o.s.d.s.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	.. 19 frames truncated
```	
Seems like the OutParameters object is not being populated and when calling the getInt() method outside the handle.createCall callback method it fails.

The following workaround works but is this the intended behaviour? If so then maybe the 3.43.0 should be marked as a breaking change?
```
public int fetchNumberOfPets_3_43_0() {
		long start = System.nanoTime();
		try {
			return getJdbi().withHandle(handle -> {
				try (Call call = handle.createCall("call pets.countPets(:x)")) {
					OutParameters result =  call
							.registerOutParameter("x", Types.INTEGER)
							.invoke();
					return result.getInt("x");
				}
			});
		} finally {
			metrics.reportDBDelay(Duration.ofNanos(System.nanoTime() - start));
		}
	}
```

**Comment by stevenschlansker** [comment]
Yes, all statement resources should be consumed before closing the statement. In this case, that means you should read OutParameters before closing the Call or Handel.

@hgschmie recently added support for returning ResultSet from OutParameters, which probably led to the change in behavior. I don't think we understood the breaking nature of the change.

Is it feasible to update your code to use the returned resources properly (read before close)? If not, we can consider a switch or other workaround to continue to allow the old behavior.

**Comment by RobbanHoglund** [comment]
I believe that this might affect a lot of users. Since this breaks the behavior I think it would be wise to state this behavioral change in the release notes.

**Comment by hjortling** [comment]
We can live with this "stricter" implementation and update our code. Although I agree with @RobbanHoglund and also think that this could be made even more clear in the documentation 

Thanks for your assistance!

**Comment by stevenschlansker** [comment]
Let's leave this open at least until @hgschmie can take a look. If nothing else, we can add a docs note.

**Comment by hgschmie** [comment]
Will find time this afternoon.

**Comment by RobbanHoglund** [comment]
The fact that it is even possible to use the _OutParameters_ API in an incorrect way is "unfortunate". I think that the javadocs could be improved to clearly explain the proper way of how to use  _OutParameters_ (like a similar way how the relationship between the Resultset and Statement is played)

**Comment by stevenschlansker** [comment]
Yes, agree, let's at least update the docs as part of this issue.

**Comment by stevenschlansker** [comment]
I opened a PR to at least note this in the release notes and javadoc - please take a look.

**Comment by hgschmie** [comment]
Thank you, @stevenschlansker for working on this.

@hjortling @RobbanHoglund Sorry for breaking your code. Here is some clarification about the changes and why this affects you:

The pre-3.43.0 code fetched any outparameter right after the internal `CallableStatment` returned and stored them in the call object. So when that got closed (in the example above when the `withHandle` callback returned), this affected "live" object such as a ResultSet but others (e.g. a String or integer result) were unaffected.

With the introduction of ResultSet support which is needed for some databases (cough MS SQL cough), this is no longer possible. The JDBC standard recommends consuming this ResultSet before any outparameter methods on the CallableStatement can be called. So by calling them right away, it was impossible to actually retrieve the ResultSet. The 3.43.0+ code replaces the direct parameter retrieval with callbacks so that the values are only retrieved when an actual method on the OutParameters object is called. But the code above closes the CallableStatement when execution returns from the `withHandle` callback so the database returns "closed statement" when the code finally executes e.g. `getInt` on the callable statement. 

This only ever worked by accident/because. However, Hyrums's law states that users will rely on behavior even if it is unintentional, so this is on me to break your code. Sorry for that. 

The example above can be rewritten like this:

```java
public int fetchNumberOfPets_3_42_0() {
    long start = System.nanoTime();
    try {
        int result = getJdbi().withHandle(handle -> {
            OutParameters outParams - handle.createCall("call pets.countPets(:x)")
                .registerOutParameter("x", Types.INTEGER)
                .invoke());
	    return outParams.getInt("x");
        });
        return result;
    } finally {
        metrics.reportDBDelay(Duration.ofNanos(System.nanoTime() - start));
    }
}
```

I agree that we need to highlight this change better as it has potential to affect a lot of users that use stored procedures.

**Comment by hgschmie** [comment]
I think we can close this issue, as we improved the docs (thanks @stevenschlansker).

**Comment by Drumbl** [comment]
Hello @hgschmie and @stevenschlansker. 
I am an automated quality tester. In our work, we use this library through JDBI annotations and in conjunction with Guice from Google.
We have 3 classes: 

1. Class module in which the JDBI driver is configured and created.

```java
public class DBModule extends AbstractModule {

    @Provides
    @Singleton
    protected Jdbi provideJDBI(Config config) {
        return Jdbi.create(config.getJdbcUrl(), config.getUsername(), config.getPassword())
                .installPlugin(new SqlObjectPlugin());
    }

    @Provides
    @Singleton
    protected SomeDao provideDao(Jdbi jdbi) {
        return jdbi.onDemand(SomeDao.class);
    }
} 
```
2. DAO interface.
```java
public interface SomeDao {
    @SqlCall("....")
    @OutParameter(name = "result", sqlType = Types.DATE)
    OutParameters getDate();
}
``` 
3. The test itself.
```java
@Guice
public class DbTest {

    @Inject
    private SomeDao someDao;

    @Test
    public void check() {
        Date date = someDao.getDate().getDate("result");
        assertThat(...);
    }  
}
``` 
Before version 3.43.0 it was very simple, convenient and most importantly fast. For us, this is the main feature of this library. 
Now we don't understand how to use the library as easily with updates, the onDemand() method can only be used with @SqlQuery. 
The update breaks the whole point.
Can you add another annotation or something similar to bring back the old functionality?

**Comment by stevenschlansker** [comment]
Hi @Drumbl , as Henning described above, the code that you show here is not correctly using resources. When the SomeDao method returns, the Handle is released, and the OutParameters are closed. There's a couple hopefully simple ways to fix this. First idea is to extract the result before returning:

```
default OutParameters getDate() {
    return getDate0(...).getDate("result");
}

SqlCall("....")
@OutParameter(name = "result", sqlType = Types.DATE)
OutParameters getDate0();
```

This has the advantage of hiding the database specific OutParameters inside your DAO object, avoiding leaking the abstraction out to the caller.

If you need to do more complicated processing, you can hold the dao open manually:

```
public interface SomeDao extends SqlObject {
    @SqlCall("....")
    @OutParameter(name = "result", sqlType = Types.DATE)
    OutParameters getDate();
}

Date date = someDao.useHandle(h -> someDao.getDate().getDate("result"));
```

If neither of these can possible work, we can consider adding a flag to bring back the old behavior, but there is good reason to move away from it since the database driver could break it at any time.

**Comment by Drumbl** [comment]
@stevenschlansker thanks for the answer. I've tried implementation options. We have a huge project, I showed the solutions to my colleagues. And they didn’t like it, it requires a lot of corrections to a stable code.

The first option works, but looks like a hack and requires additional wrappers. There is also additional code to handle queries with a large number of output variables. I'll have to add additional models or a collection to store the data and then process them later.

The second option doesn't work because the useHandle method doesn't return objects. There is a withHandle method, but it already increases the amount of written code, and with it I also received an error: Could not get OUT parameter from statement.

I have little understanding of the problem you wrote about above. You wrote that you could add some kind of flag to switch to the old implementation, but I don’t really like this option, because it also looks like a hack. 
It might be better to add an annotation that intercepts the connection and stores the result in OutParameters before the connection is closed. And inside the implementation, make the code that you suggested above in the first option. Or make a separate class that would return a value in the form of a collection or map.

I don’t understand why it’s impossible to receive data, save it, and then close the connection.
Excuse me. =))))
