### ISSUE TITLE
Using new Query.stream() method introduces possibility of resource leaks.

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#272]
The stream needs to be eagerly closed by the caller, e.g. in a try-with-resources block.

If possible, we should find a way to automatically close the stream when any terminal operation is invoked on a query stream, e.g. `findFirst()`, `collect()`, or `reduce()`.

**Comment by stevenschlansker** [comment]
We could attach an [onClose](https://docs.oracle.com/javase/8/docs/api/java/util/stream/BaseStream.html#onClose-java.lang.Runnable-) handler?
I think we still need to declare "returned Streams own database resources, and *must* be closed or you will leak".  Even with an `onClose`, you could throw an exception, or otherwise terminate abnormally...

I wish there was a way to declare this and have it statically verified, or something like that.

**Comment by qualidafial** [comment]
`onClose` handlers are not called for terminal operations--only on explicit calls to `close()`. http://stackoverflow.com/questions/27381329/do-terminal-operations-on-streams-close-the-source

I'm working on a possible solution for this: add an `onClose` handler as you suggested, and wrap the stream in a thin wrapper which calls `close()` after any terminal operation is called. It's not perfect, but it's not bad as a best effort approach.

Even with this in place, I would also favor putting a big scary disclaimer in the javadoc on the `ResultBearing.stream()` method.

**Comment by qualidafial** [comment]
Submitted PR #273

**Comment by qualidafial** [comment]
Closing this ticket. Let's move any further discussion into #273
