### ISSUE TITLE
Unable to set a null value via JDBI and Sybase JConn4

### ISSUE THREAD

**Issue by dlei** [jdbi/jdbi#299]
`@SqlCall("{:retVal= exec sp_CountryCredit_Insert :clientID, :country, :user}")
    OutParameters insertClientCountryCredit(@Bind("clientID") long clientID, @Bind("country") String country, @Bind("user") String user);`

when `country` is bind to NULL, then I'm getting 

>  JZ0SL: Unsupported SQL type 0. 

after a closer look, the jdbi is trying to do

>  statement.setNull(position, Types.NULL);

I override it to 

>  statement.setNull(position, Types.VARCHAR);

and then it seems to work. Is there anything that I'm missing? If not, is it possible to make jdbi smarter to accommodate this situation?

**Comment by stevenschlansker** [comment]
Unfortunately, it seems likely that fixing this for Sybase will break it for some other database vendor -- is there no possibility that Sybase can fix their driver to understand null types?  Do you have a proposed way to fix this?

I'll try to look at this at some point, but it is very difficult to make changes that involve proprietary drivers -- we have no way to test that we actually fix the problem, and don't break e.g. Oracle :(

**Comment by kristwaa** [comment]
Just wondering, has  using the "proper JDBC way" been attempted?
I.e. specifying the type in the call to setNull?
Out of curiosity, is it a design decision to avoid any kind of database system specific code in the JDBI core?

The above could be done by querying the metadata, but I don't know if this would impose a high performance overhead in JDBI (the performance hit could also differ between database systems). Also, I don't know if all database systems provides accurate type information, or if there are special cases where the type cannot be determined at the required point of time.

Just to demonstrate what I mean, I coded a small, naive example:
https://github.com/kristwaa/jdbi/commit/5258abf2a9d1a8855af12c2e1a8d72ea8d6d3083

**Comment by stevenschlansker** [comment]
From @dlei 's description, it sounds like he has shown that the "proper JDBC way" of using `Types.NULL` does not, but `Types.VARCHAR` does.

We can introduce vendor specific code if necessary.  I just want to make sure that there is no possibility of a driver fix first.  It feels like this is something that the Sybase driver *should* support.

Has anyone filed a ticket with them?  Since this is a paid offering, presumably you have a support contract and can get some response from the vendor?

If they refuse to fix it, we could certainly consider a patch that improves this under two conditions:

* No visible effect on non-Sybase databases
* No performance penalty on non-Sybase databases

Seem reasonable?

**Comment by kristwaa** [comment]
Yes and no - it depends on your point of view :)

The JDBC issue here might be that `Types.NULL` is not really a type... The wording in the Java API JavaDocs hints at this, describing [Types.NULL](https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html) as the constant for a value.

Apache Derby also barfs on `setNull (i, Types.NULL)`. Investigation shows this is not due to a technical limitation - it's about adhering to the JDBC specification. I plan to check with the community if using `Types.NULL` can be allowed for convenience.

**Comment by stevenschlansker** [comment]
Huh.  Okay, this is all very confusing.  Why does the `Types` class have a constant for a "value"? 😞
I'm happy to accept any better approach to doing this -- as long as it doesn't cause regressions in other databases.  Let me know if you think you have a good cross-database way of doing this, or we could consider vendor-specific code if absolutely necessary.

**Comment by qualidafial** [comment]
This makes me seriously consider rejecting null argument values in v3 without either a SQL type, or a class / generic type to help resolve the SQL type.

**Comment by stevenschlansker** [comment]
In jdbi 3, you can now install vendor plugins that customize handling of types.  While we probably won't build a Sybase one ourselves, it'd be easy for someone to contribute it!

**Comment by qualidafial** [comment]
It might make sense to add a configuration in v3 to override the SQL Type for NULL, then let database-vendor-specific plugins override it.

**Comment by qualidafial** [comment]
I'm very seriously considering just disallowing an untyped null outright. Will investigate the impact in our tests.

**Comment by kristwaa** [comment]
Haven't been able to follow up on this. Do you have any examples of relevant "database plugins" to deal with this kind of issue? I believe Apache Derby has similar issues as Sybase ASE (I tested with the jTDS driver, not jConnect).

As for disallowing untyped null, where will the required type information come from?
Are you thinking of obtaining it through metadata from the database, or by using metadata specified through JDBI?

I also suppose those using drivers that do support untyped nulls would like to continue using that for performance or convenience reasons.

**Comment by kristwaa** [comment]
If this is a global type-independent knob it would be handy for databases where a single type can be used for all types of columns (for instance `Types.NULL` vs `Types.OTHER`).

In database systems where the type has to be the type of the relevant column / expression it won't suffice.

**Comment by qualidafial** [comment]
> As for disallowing untyped null, where will the required type information come from?
Are you thinking of obtaining it through metadata from the database, or by using metadata specified through JDBI?

The idea was that this would be supplied explicitly to JDBI.

In the core API, this means switching from `SqlStatement.bind(index, null)` to e.g. `SqlStatement.bindByType(index, null, String.class)`.

However I've realized that this restriction would make methods like `bindMap()` and `bindList()` throw an error if the map/list contained any null values. This is a serious enough drawback that I'm looking for other alternatives.

The next thing I want to try is to call `setObject(columnNumber, null)` instead of `setNull(columnNumber, someTypeConstant)` and see how widely compatible that approach is.

If we can't find a one-size-fits-all approach, we'll have to set up some kind of configuration so you can swap out behaviors depending on the database vendor.

**Comment by kristwaa** [comment]
> The next thing I want to try is to call setObject(columnNumber, null) instead of setNull(columnNumber, someTypeConstant) and see how widely compatible that approach is.

A datapoint from the Apache Derby source code:

>         // JDBC Tutorial and Reference books states in the PreparedStatement
>         // overview, that passing a untyped null into setObject() is not allowed.
>         // JCC disallows this, basically SQL can not handle a untyped NULL.
>         // Section 25.1.6 (Third edition), 24.1.5 (Second Edition)
>         //
>         // However, the following update was made to the JDBC API:
>         // "Note: Not all databases allow for a non-typed Null to be sent to
>         // the backend. For maximum portability, the setNull or the
>         // setObject(int parameterIndex, Object x, int sqlType) method should
>         // be used instead of setObject(int parameterIndex, Object x)."
>         // Based on the above sentence, passing null is now allowed by Derby.
>         // See DERBY-1938 for details.

Internally Derby consults the metadata and issues a `setNull` with the type specified.

**Comment by qualidafial** [comment]
My latest thinking is to introduce a configuration to `Arguments`:

```java
public class Arguments implements JdbiConfig<Arguments> {
   ...

  public Arguments setUntypedNullArgument(Argument);

  public Arguments setUntypedNullSqlType(int sqlType) {
    setUntypedNullArgument(new NullArgument(sqlType));
  }
}
```

Then, in e.g. `PostgresPlugin` we would call `jdbi.getConfig(Arguments.class).setUntypedNullSqlType(Types.OTHER);`.

**Comment by stevenschlansker** [comment]
Or we could consult the `ResultSetMetaData`, which provides a `getColumnType(int columnIndex)`

**Comment by stevenschlansker** [comment]
Now that jdbi3 lets you configure the untyped null, we'll consider this closed.  If you need special handling it should be easy to configure it yourself or contribute a plugin that does so.

**Comment by lwpro2** [comment]
Just encountered same exception here. The message itself is not very clear. But it's due to same cause, basically not nullabe columns being passed with null value.
