### ISSUE TITLE
Split "query" / "update" concept apart from SqlObject annotations

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#301]
`@SqlUpdate` and `@SqlQuery` and the like aren't quite right.  For example, if you want to `UPDATE` a record and return the new values, you have to write:

``` java
@SqlQuery("INSERT INTO ig_token(user_id, access_token) VALUES(:userId, :accessToken) RETURNING *")
```

Really the "query" part means "returns a value for mapping.
Maybe we should split this up a bit, e.g.

``` java
@SqlStatement("INSERT ... RETURNING *")
@MapResult
MyBean doSomething(...);
```

vs

``` java
@SqlStatement("UPDATE ...")
@ModifiedRowsResult
int doSomething(...);
```

**Comment by qualidafial** [comment]
Could also roll e.g. `@GeneratedKeyResult` into this

**Comment by qualidafial** [comment]
For brevity I think it makes sense to keep `@MapResult` be implied as the default return type transformation if you don't specify it.

Also, what if we renamed `@SqlStatement("select ...")` to just `@Sql("select ...")`?

**Comment by stevenschlansker** [comment]
Default could be "generated keys if available, else result set if available, else update count"

**Comment by qualidafial** [comment]
Would the `@OutParameter` ticket satisfy this?

**Comment by qualidafial** [comment]
The SQL method annotations are just mirrororing the fluent APIs, so it's likely that whatever changes we make to sqlobject would also be appropriate for core. e.g. to execute the statement `INSERT INTO FOO (a, b) VALUES (:a, :b) RETURNING *` in core, you have to use `Query`, instead of `Update`.

This makes me wonder whether we should just have a single SQL statement class, and maybe certain query-centric methods convert to a `ResultBearing` mode.

**Comment by qualidafial** [comment]
I'm not sure I still agree with this ticket. I think I'd rather continue to use `@SqlUpdate("...")` and `@SqlQuery("...")` with the obvious semantics those imply, than have to use two annotations per method e.g. `@Sql("...") @MapResult`.

**Comment by stevenschlansker** [comment]
I guess if we decide to change it later, we can leave the existing annotations and just add new ones.  So we can close this and reopen later if we think of something cool.
