### ISSUE TITLE
All the various things SQLStatement uses should be on StatementContext

### ISSUE THREAD

**Issue by brianm** [jdbi/jdbi#324]
Instead of having instance vars on SQLStatement and friends, the various things like the Binder and Foreman should be obtained from the Context

**Comment by qualidafial** [comment]
Are we getting value out of having `StatementContext` an interface with separate `ConcreteStatementContext` and `TestingStatementContext` implementations?

**Comment by brianm** [comment]
No, we are not.

**Comment by qualidafial** [comment]
Copy that. I'll plan on coalescing those types when I get to this.

I also noticed that `StatementContext` still has several methods that are specific to sqlobject, notably `getSqlObjectType` and `getSqlObjectMethod`. I actually don't know what purpose those methods serve. Logging? Vestigial tail left over from the old design?

Another observation: we have two types of context/metadata/whatever that we track: configuration (including all the registries), and statement metadata (which are only relevant in the context of a `SQLStatement`).

Rather than slap a StatementContext on DBI and Handle, where the statement-specific properties make no sense, I think we should extract a class out of `StatementContext` that comprises all the configuration, and make that an accessible member of `StatementContext`. No idea what to call that class though. `JdbiConfiguration`? `Registries`?

**Comment by qualidafial** [comment]
I've started work on this on the `jdbi3-refactor-registries` branch. The registries, statement locator/rewriter, and timing collector are all part of `JdbiConfig` which is internal-only.

**Comment by qualidafial** [comment]
Opened PR #337
