### ISSUE TITLE
Support asynchronous return types in SQL Objects

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#770]
A colleague brought up that JDBI doesn't offer support for asynchronous query execution. It would be neat if we could instrument JDBI in some way, so that a SQL method could return e.g. `Future<List<User>>`, or an RxJava `Observable<User>`, implying that we're executing the query on some other thread and allowing the current thread to process other things while we wait.

The dominant `CollectorFactory` approach we're using now implies synchronous processing, so we would need to target a higher layer of abstraction.

We do have a `ResultProducer` interface for returning results of any old type, that might make a good place for somebody to plug this in.

Idea:
* Introduce `ResultProducerFactory` (ugh) similar to `CollectorFactory`.
* Change `ResultProducers` into a config class that acts as a `ResultProducerFactory` registry.
  * Keep the existing static `ResultProducer` methods.
  * Advise users in the javadoc that they should only register producers for types that unambiguously imply a specific result producer--e.g. `returningUpdateCount()` should not be registered for `int`, because you could plausibly want an update count _or_ a value from the database depending on the scenario.
* Preregister result producers for Iterable, Iterator, Stream, collectables (i.e. types for which a `CollectorFactory` is registered), and single values.
* Refactor ResultReturner.forMethod() to use the result producer factory, instead of hardcoding for each result type.
* Add methods on our SqlStatement types (wherever it makes sense) to get a result by type--similar to the collectInto(GenericType<T>) method on ResultBearing.

I don't propose we support `Future<T>` within the project as API--there's too many variables for us to pick a strategy that would work for everybody. But we _could_ do a proof of concept in tests to show that it's feasible for users to plug that in.

Also, I'm targeting post-v3 for the moment--I think this might be neat, but wouldn't want it to hold up release.

@stevenschlansker @arteam thoughts?

**Comment by stevenschlansker** [comment]
I'm not actually sure how this would work. JDBC pretty strongly ties a connection to a thread of execution - do you have a plan for how we would provide asynchronous results without managing a worker thread pool? I don't see how it would work. You could simulate async with a worker thread pool but that seems no better than using the application's thread pool synchronously in most cases.

I think we would need driver support to actually do this.

**Comment by arteam** [comment]
I agree with Steven. JDBC is synchronous by design and I think it would be rather hard to adapt to a workflow with async communications. Moreover, even if we used a custom protocol, and implemented this in the library, I believe there's no much sense in sending async requests to a database from the user's perspective. The database has a limited amount of resources (if it's not a distributed cluster behind a proxy). There is a little gain in opening a couple of hundred TCP connections and throwing a lot of traffic in it. The database will not be able to process all them concurrently, and it doesn't have any mechanism to balance/control this load. Even in the best case when the data are cached in the memory, there is still an overhead of parsing queries and building an execution plan which are CPU bound. I believe the RxJava community recommends wrapping JDBC interactions in a custom executor with the fixed amount of threads and have a good-tuned connection pool.

**Comment by stevenschlansker** [comment]
Maybe this issue should be restated as, "determine how to best support reactive streams usage" http://www.reactive-streams.org/announce-1.0.0, rather than specifiying a specific technical detail of how it might work.  Or was the use case really specifically that you want a `Future` returned?

**Comment by qualidafial** [comment]
Thanks for your feedback guys. This is some good food for thought.

There are really two parts to this ticket: asynchronous support, and support for collector-hostile return types. Let's close this ticket and I'll open up another one once I've had a chance to rethink this.

**Comment by toadzky** [comment]
I'm sure that some people would want to have a `Future`, `Promise`, or an `Observable`. Personally, I like promises and observables, depending on what I'm doing. 

I'm the one who asked @qualidafial about this in the first place. I would like to see JDBI work similarly to Retrofit, where there is a hook of some kind to register a container factory. I mostly care about the feature in the SqlObject api, since that's the way I used JDBI mostly. I can always do work around where I submit a callable to a thread pool and use the future returned, or wrap the SqlObject in something that does the RxJava, but it's something I have to manually do every time. More and more things are asynchronous, and despite the JDBC not following that trend, I would like to see libraries like this support async so I don't have to do the wrapping on every project and every SqlObject.

**Comment by stevenschlansker** [comment]
Having an integration library with `rxjava` or reactive-steams makes sense.  That library could expose `CompletableFuture` as a collector type.  But at least for the time being all we would be doing under the hood is having a worker thread pool, same as you do -- so it will not truly improve scalability.

**Comment by qualidafial** [comment]
I want to clarify what was actually being proposed.

I don't think we can (or should) implement a worker thread pool in JDBI proper. I'm not even suggesting we support `rxjava` or other asynchronous libraries directly within JDBI.

What I _am_ suggesting, is that it should be possible for users or third-party libraries to plug in support for these use cases.

The root problem is that `Collector` is synchronous. That is, when you call `collect(Collector)`, it is traversing the entire result set, collecting every element into the collector before returning. The is like.. the opposite of what e.g. `rxjava` wants to do.

The focus of this ticket was to add a `ResultProducer` registry to core, so that people can reasonably add support for return types where `Collector` is not a great fit.

**Comment by qualidafial** [comment]
Also worth reiterating: even if we do add the `ResultProducer` registry, there is still the hurdle of how to juggle JDBC connections / JDBI handles across threads, as @arteam pointed out.

**Comment by stevenschlansker** [comment]
Right, and I think that quickly runs into the problem we highlighted above: JDBC is utterly synchronous and you cannot write a solution that provides the asynchronous interface without blocking and without managing a worker pool.  Would love to be proven wrong 😄
