### ISSUE TITLE
Add JdbiPlugin.customizeStatement?

### ISSUE THREAD

**Issue by apjoseph** [jdbi/jdbi#794]
I essentially have a plugin configuration class that has some settings which need to be handed down and copied at the DB/Handle/Statement scopes to ensure I'm not overriding settings at a higher level. Seems the only way I can accomplish this is via attributes and `define` (there doesn't appear to be a plugin registry). I can use the `customizeJdbi`, `customizeHandle` from `JdbiPlugin` for the DB and Handles, but there is no `customizeStatement` for modifying statement settings. Is this functionality defined/set elsewhere?

**Comment by qualidafial** [comment]
There are currently no API hooks to customize every statement.

We do have `BaseStatement.addCustomizer(StatementCustomizer)`, but it sounds like you want something more global.

Could you help me understand your use case?

**Comment by apjoseph** [comment]
Basically I am dealing with a Jackson `ObjectMapper` and other common plugin specific properties that need to be passed to mapper factories, mappers and sql customizing annotations. I want to be able to override these properties at the handle/statement levels. Currently the library I am working with does this via `define(key,value)` which works fine but seems more appropriate to have something like 
```
class MyCustomPluginSettings extends JdbiPluginSettings<T extends JdbiPlugin> {

  private ObjectMapper objectMapper;
  private String configurationProperty1;
  private Integer configurationProperty2;

  //This method would be called each time a new Handle/Statement/DB is instantiated and allow for properties to be overridden at each level.
  @Override 
  public MyCustomPluginSettings copySettings() {
     ...
  }

  //getters and setters
  ...
}
```

You would then be able to grab/modify the plugin's settings via:

`jdbi.getPluginSettings(MyCustomPluginSettings.class)`
`handle.getPluginSettings(MyCustomPluginSettings.class)`
`statementContext.getPluginSettings(MyCustomPluginSettings.class)`

This would also ensure that fewer plugin developers are setting critical configuration settings via 'define("_my_custom_plugin_property1,object) -which  would result in less headaches when developers arbitrarily decide to change the string key names without informing library users or when the key names inevitably conflict with user defined properties or other plugin properties.

**Comment by qualidafial** [comment]
Have you looked at the new `JdbiConfig` mechanism?

**Comment by apjoseph** [comment]
@qualidafial That was my first thought. It didn't seem there was a way to actually register a class based on the javadoc, but in looking at the source code for `get(Class<C> configClass)` I now see the comment: "Creates an instance on-demand if this registry does not have one of the given type yet." 

So if I were to implement my `MyCustomPluginSettings` using the `JdbiConfig` interface, all I would need to do is implement `createCopy()` -which is called for all registered `JdbiConfig` instances each time `configRegistry.createCopy()` is executed. Looks like the latter method is in turn called each time a Db,Handle or BaseStatement is instantiated, correct?

**Comment by qualidafial** [comment]
Exactly right.

If your config class is interested in talking to other config objects, you
can also implement the setRegistry method, which is called immediately
after any config object (or copy) is instantiated by the registry.

On Apr 6, 2017 6:09 PM, "Andrew Joseph" <notifications@github.com> wrote:

@qualidafial <https://github.com/qualidafial> That was my first thought. It
didn't seem there was a way to actually register a class based on the
javadoc, but in looking at the source code for get(Class<C> configClass) I
now see the comment: "Creates an instance on-demand if this registry does
not have one of the given type yet."

So if I were to implement my MyCustomPluginSettings using the JdbiConfig
interface, all I would need to do is implement createCopy() -which is
called for all registered JdbiConfig instances each time
configRegistry.createCopy() is executed. Looks like the latter method is in
turn called each time a Db,Handle or BaseStatement is instantiated, correct?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jdbi/jdbi/issues/794#issuecomment-292370461>, or mute
the thread

**Comment by qualidafial** [comment]
@apjoseph Did using JdbiConfig help resolve your problem?

**Comment by stevenschlansker** [comment]
Feel free to reopen this issue if the configuration infrastructure is not sufficient.
