### ISSUE TITLE
Recommended way to implement record versioning?

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#797]
I'm playing with the thought of adding record versioning to my tables, to avoid data checked out a while ago silently overwriting data that was updated in the meantime. The stuff that's talked about here: https://www.intertech.com/Blog/versioning-optimistic-locking-in-hibernate/ . I don't need to keep copies of the old data, just prevent my user from checking out a current record twice, persisting one checkout with a changed column, and then persisting the other checkout on top of it with a different change, wiping the first change into oblivion.

Is there a particular way this could be done conveniently with jdbi?

It would kinda suck to have to wrap all of my single-statement @Query calls in transactional methods just to check the version numbers before calling the statement.

The best thing I can think of off the top of my head is simply an update trigger on each table, where on update the new row.version is compared to the current row.version.

I'm kind of drawing a blank otherwise, can't seem to think of much. No java magic based on a generic/uniform versioning column and some annotation magic comes to mind either...

**Comment by qualidafial** [comment]
The simplest way is to do a version check and set in your update statement, and verify the result:

```
@SqlUpdate("update product set name = :name, cost = :cost, version = 1+:version " +
    "where id = :id and version = :version")
int updateProduct(@BindBean Product product);
```

If `updateProduct` returns zero, then the row was not updated. This could be because no record with that ID exists, or because the version is out of date.

This is basically how Hibernate does optimistic row locking with the `@Version` annotation.

Are you using v2 or the v3 beta?

**Comment by stevenschlansker** [comment]
You could consider `SERIALIZABLE` level transactions.  In a MVCC database like Postgres, it sounds like it behaves exactly as you want -- transactions complete optimistically, and if there is ever a conflict, one of them aborts and has to retry on the updated value.

**Comment by TheRealMarnes** [comment]
@stevenschlansker it's not about concurrent transactions, I always use serializable anyway. Its about the application persisting the same record twice (some time apart), both times with a different change from the same source state. Whichever commits second will overwrite the first update's changes because I update entire records, not individual columns.

I like @qualidafial 's query-integrated check's simplicity, but it lacks one thing I think is important; I'd prefer it to throw an exception rather than just not update anything and return a result that needs to be checked. A trigger could throw an exception and be present regardless of the query doing the check (eleminates some redundancy and room for error if there are multiple update queries). I'm on jdbi v2.

I had a thought in the meantime that instead of a counter, a random uuid could be used. A counter carries counter semantics with it, while uuids are more like a fingerprint. I'd just compare the record's current fingerprint to the fingerprint in the update (which carried over from when it was checked out). Making the check column a hash of the other column values could work nicely too, as a fingerprint derived directly from the record's state instead of just randomly. Updates might become costly then of course, with all those calculations.

On the topic of jdbi though, I guess there isn't really any particular utility to make life easier here? Just a matter of generic db and application design?

**Comment by stevenschlansker** [comment]
Yeah, I'm not really seeing a feature for us to implement that would help.  You are very much in the "application design" part of the stack.  If you come up with some way jdbi can help we'd be all ears but nothing comes to my mind.

**Comment by TheRealMarnes** [comment]
I talked about it with a more experienced friend of mine, and we agreed it's either gonna be an update trigger or a check on the returned number of updated rows. One thing we did vaguely think about was a sort of wrapper around updates that verifies the expected number of rows was updated. I'm thinking something along the lines of adding a property to @SqlUpdate like so:

```
@SqlUpdate(query = "update Component set name = :name, ... where id = :id", expectedRows = 1)
int update(...);
```

throwing an exception if the returned int != expectedRows. I can see this having use in queries specifically meant to update a specific number of records, which I guess will usually be 1 for simple entity updated, or some exotic case where n-size groups of records are updated together, like flagging all n players of a team in a match as dead or something.

What do you think about that?

**Comment by stevenschlansker** [comment]
I think that's a reasonable feature request.  If you want it in v2 though we'd probably ask that you contribute it -- most core dev time is spent on v3.  I think since it's a concrete feature ask it should probably be filed as a separate ticket so that we can discuss.

**Comment by TheRealMarnes** [comment]
Before I get started on it, I think it'll only work in a transaction. If the value is checked at return time, the thrown exception will abort the ongoing transaction. If the method is called stand-alone though, the update will be succeed and then you'll get an exception that doesn't abort anything... Kind of a dangerous pitfall.

**Comment by qualidafial** [comment]
As long as the transaction behavior of `expectedRows` is well-documented in the javadocs, I'm on board.

**Comment by stevenschlansker** [comment]
Or it could be a separate composeable annotation.  For example you might want to apply it to each result row in a `@SqlBatch`

**Comment by stevenschlansker** [comment]
Feel free to reopen if anyone feels more discussion is necessary.

**Comment by xak2000** [comment]
@stevenschlansker It's not clear from this discussion if this feature was implemented in 3.x or not? I didn't found any documentation on it, so I suppose the answer is "no"? :)

By the way, I like the idea with `@ExpectedRowsCount` annotation, but at the same time I think about: what exception it will throw? The primary reason to have this annotation is optimistic locking. So it's good to throw some kind of `OptimisticLockException` (similar to [javax.persistence.OptimisticLockException](https://docs.oracle.com/javaee/7/api/javax/persistence/OptimisticLockException.html)). But then, maybe name of this annotation shouldn't be `@ExpectedRowsCount`. It looks too generic for that exception. Maybe the annotation should be named `@UseOptimisticLock` or something like this, so be focused on exactly this usecase instead of more generic use case of checking rows count. So, there is still something to think about.

But anyway, the feature is good I think. Because if you explicitly crafted the query to manage a `version` field (basically do an optimistic locking), it would be strange to check the result count in service layer of the application. DAO layer looks more appropriate here.
