### ISSUE TITLE
Multiline strings with @SqlQuery/@SqlUpdate

### ISSUE THREAD

**Issue by jhaber** [jdbi/jdbi#888]
In our codebase we use the SQL Object API almost exclusively, with all the queries defined in-line. Since Java doesn't support multiline strings, this doesn't work very well for longer queries. We need to manually split over multiple lines, so we start to lose readability and it also becomes error-prone (can easily forget to pad with a space, causing the query to be invalid). However, we like the convenience and simplicity of defining the queries in-line, so I started thinking about ways to make this work better. One promising option is to define the query inside a comment like [this](https://gist.github.com/isa/878708#file-multilinestring-java-L51-L56). So a JDBI example would look like:

```java
public interface MyDAO {
  
  @SqlQuery(/*
  SELECT my_table.*
  FROM my_table
  INNER JOIN other_table ON (other_table.id = my_table.id)
  WHERE other_table.name = :name
  */)
  List<Stuff> findByName(Bind("name") String name);
}
```

You could do some build-time magic so that the class file ends up with the actual query inside the annotation, then no changes are needed at runtime. Or you could have a hybrid approach, where less magic happens at build time, and then a bit of magic happens at runtime (maybe an annotation processor that stores the SQL somewhere, and a custom statement locator that knows how to look it up). I just wanted to see if this was something you guys had thought about before and if the suggested approach seems tenable (presumably this would live in a separate library, not JDBI itself)

**Comment by qualidafial** [comment]
In principle I like this idea, and it might be possible to accomplish with a SqlLocator. I'm not certain Jdbi is the right home for it, although I'm open to being convinced otherwise.

One reservation I have is that what you propose seems like a brittle workaround to a Java language deficiency. But if Java 9 or 10 starts supporting multiline strings then we'd be stuck with a vestigial tail until the next major version. Sadness.

Do you use IntelliJ? It has an excellent feature that does syntax highlighting and validation in embedded code (e.g. when embedding SQL in a Java string). Put the cursor over a SQL string, invoke the "Find Action" command (Ctrl+Shift+A on Linux), and search for "Inject language or reference," then select SQL or your specific database vendor. Once you've injected a language into the annotation attributes and method parameters in Jdbi's API, they will be highlighted and validated as SQL everywhere you use them.

**Comment by jhaber** [comment]
I agree that this can be mitigated to some extent by an IDE, and that it doesn't belong in JDBI proper. I was mainly looking for a sanity check and to see if you had investigated options like this already. I believe the scope of Java 9 is already set in stone and doesn't include multiline strings, so the chances of being able to use them before 2020 seems to be pretty slim. I'll play with a few approaches and report back if I find anything promising 😃

**Comment by jhaber** [comment]
I made a small library that seems to work ([here](https://github.com/HubSpot/jdbi-javadoc-queries)):

```java
  /**
   * SELECT *
   * FROM table
   * WHERE id = :id
   */
  @SqlQuery
  Widget getById(@Bind("id") long id);        
```

 At the moment queries can only be written as Javadoc comments. It also requires you to set a custom statement locator, which means it doesn't play well with `@BindIn` or `@Define` (which also require statement locators).
