### ISSUE TITLE
Binding of value objects without getter methods

### ISSUE THREAD

**Issue by static-max** [jdbi/jdbi#895]
I like the concept of value objects, where attributes are _public final_, e.g.:

```java
public class User {
  public final int id;
  public final String name;
  public User(int id, String name) {
    this.id = id;
    this.name = name;
  }
}
```

So you don't have to pollute your classes with getters and setters. `@BindBean` needs getter methods, so I would like to ask if a PR might be accepted providing this use case. Name could be `@BindValueObject` for example. Every public(visible?) field would automatically qualify for binding.
I'm thinking about creating a new `NamedArgumentFinder` and adding it to `org.jdbi.v3.core.statement.SqlStatement` just like `@BindBean` does.

What do you think?

**Comment by stevenschlansker** [comment]
Yes, @pennello was actually just expecting this the other day as well.  I think a binder that binds (non-private?) fields makes a lot of sense.

**Comment by qualidafial** [comment]
Should this just be folded into `@BindBean`?

**Comment by FredDeschenes** [comment]
I looked into adding this feature and ran into some slight issues/annoyances if you want to include it into `BeanPropertyArguments` aka `@BindBean`.

- If merging with `@BindBean` it will add some overhead, although it should be pretty minimal considering the amount of reflective stuff going on in this function anyway.
- What happens if we can match both to a field and a regular bean getter?
  - If merging in the same `NamedArgumentFinder` (ie. BeanPropertyArguments), we can at least catch the fact that both exist and display a warning. We could also add something in the `@BindBean` annotation to let users decide which one to use on a case-by-case basis.
  - If not merging, which one should be prioritized?

**Comment by stevenschlansker** [comment]
I'm not too worried about overhead -- we should inspect each `Class` once, when we first see it or in `specialize`, and cache any discovered fields.  If both a getter and field exist IMO you should call the getter.

**Comment by FredDeschenes** [comment]
Oh I wasn't aware this was cached. In that case I'll go ahead and create a PR with this (that prioritizes getters) tomorrow.

**Comment by qualidafial** [comment]
@stevenschlansker The `specialize` caching applies to `BeanMapper`, not `bindBean`. There is no caching of class metadata happening on the binding side at the moment.

It's possible we could use of an `ExpiringMap` singleton in `BeanPropertyArguments` to cache that metadata, but I think that's overkill until there's a demonstrated performance impact to worry about.

@FredDeschenes To your question about matching both getters and fields: I'd say that a bean property getter would take precedence. The most likely situation is that the getter will read from the field anyway, so there shouldn't be much difference. The `bindBean()` API name rather implies using a getter method.

I think this could be as straightforward as an additional for-loop over `beanClass.getFields()` in `BeanPropertyArguments.find()`.

I'd want to see tests demonstrating that binding public fields works, and that getter methods are given preference over fields.

**Comment by stevenschlansker** [comment]
D'oh.  We should fix that.

**Comment by qualidafial** [comment]
Caching bean / field metadata might make sense if we indexed properties / fields by name to speed up binding.
