### ISSUE TITLE
Use of `UseStringTemplate3StatementLocator` no longer allows loading queries from a file

### ISSUE THREAD

**Issue by ktalebian** [jdbi/jdbi#911]
I keep all my sqls in a separate .sql and use @SqlQuery("db/my-dao/fetch-my-dao.sql").

Everything works fine, but as soon as I add `@UseStringTemplate3StatementLocator` to the Dao interface, it can no longer find the file, and I just get a syntax error saying the string `db/my-dao/fetch-my-dao.sql` is not a valid query.

**Comment by qualidafial** [comment]
You're using v2?

**Comment by ktalebian** [comment]
@qualidafial yes I am.

**Comment by qualidafial** [comment]
Is `fetch-my-dao.sql` a StringTemplate group?

**Comment by qualidafial** [comment]
SQL Object annotations have different semantics than usual when you use the StringTemplate statement locator.

Instead of individual `.sql` files per method, all queries are collected into a single StringTemplate group file, with a `.sql.stg` extension.

A string template group file contains multiple templates, and each template has a name.

For each annotated method:
- If the annotation value looks like SQL, e.g. `@SqlQuery("select * from <table> where id = ?")`, then that value will be treated as a ST3 template, and angle-bracketed tokens like `<foo>` will be replaced with the defined attribute of that name (`foo` in this example).
- If the annotation value does not look like SQL, e.g. `@SqlQuery("fetch")`, then the template with that name (`fetch`) in the StringTemplate group will be used.
- If the annotation is bare, e.g. `@SqlQuery`, then the template with the same name as the method will be used.

**Comment by ktalebian** [comment]
@qualidafial at the moment, the `fetch-my-dao.sql` is the sql query, for example

```
SELECT * FROM MyTable
WHERE UID = uid.value
```

I prefer to have one file per query, since some queries can get quite long, but if I need to switch to `.sql.stg` to make this work, then I'll do that.

**Comment by qualidafial** [comment]
Yeah, sadly in v2, the string template annotation it's either `.sql.stg` or SQL in annotations--the choice of template engine and locator strategy are coupled.

In v3, we split this out into `SqlLocator` and `TemplateEngine` so it's possible to load SQL templates from the classpath (with `@UseClasspathSqlLocator`) and render them with StringTemplate (`@UseStringTemplateEngine`).

**Comment by qualidafial** [comment]
Closing this issue as answered.

**Comment by ktalebian** [comment]
@qualidafial followup question:

Can I overload the template methods? Let's say I have

```
@SqlQuery
List<User> getUsers();

@SqlQuery
List<User> getUsers(@Bind("autoId") final int autoId);
```

I want to have something like

```
list(autoId) ::= <<
SELECT * FROM users

<if(autoId)>
WHERE AutoId > autoId
<endif>

ORDER BY AutoId;
>>

getUsers() ::= <<
<list()>
>>

getUsers(autoId) ::= <<
<list(autoId)>
>>
```

**Comment by stevenschlansker** [comment]
As far as I know ST won't handle overloads like this, however you can always override the template name with the annotation value e.g.

```java
@SqlQuery
List<User> getUsers();
@SqlQuery("getUsersById")
List<User> getUsers(int id);
```
