### ISSUE TITLE
No method bindJpa provided

### ISSUE THREAD

**Issue by flintmail** [jdbi/jdbi#978]
Annotation @BindJpa is present in Declarative API, and documentation says that not @BindBean but @BindJpa should be used. But in Fluent API we have methods .bindBean(...), while methods like .bindJpa(...) are absent.

**Comment by qualidafial** [comment]
I'm confused--where in the documentation does it say that `@BindJpa` must be used instead of `@BindBean`?

You can use `@BindBean` with JPA entities.

**Comment by qualidafial** [comment]
To answer the broader request: it's very unlikely we will add this method to the core types.

Jdbi 2 had a single JAR with all functionality and many dependencies.

One of the goals of Jdbi 3 was to split that up into module JARs so that adopting Jdbi didn't mean adopting a kitchen sink of dependencies you want.

Because of this modularization, we cannot add methods to `jdbi3-core` types like `SqlStatement` to types that exist only in e.g. `jdbi3-jpa` or `jdbi3-sqlobject` for that matter, as this would violate modularity.

**Comment by stevenschlansker** [comment]
This would be a natural extension method, but that's not something Java can do well unfortunately.  Please feel free to suggest a concrete fix and we can reopen this issue, but otherwise unfortunately I don't think there is one available.
